// Colores representativos por equipo (puede ser string o [color1, color2] para gradiente)
export const TEAM_COLORS: Record<string, string | [string, string]> = {
  "Boca jr": "#0033A0",
  "Boca Jrs": "#0033A0",
  "Boca Jr": "#0033A0",
  Boquita: "#0033A0",
  Boca: "#0033A0",
  Dortmund: "#FFD600",
  "Real Madrid": "#FFFFFF",
  "Real madrid": "#FFFFFF",
  Liverpool: "#D00027",
  Newcastle: "#222222",
  "Manchester city": "#6CABDD",
  "Manchester City": "#6CABDD",
  City: "#6CABDD",
  "M city": "#6CABDD",
  Napoli: "#0074B7",
  "Inter Miami": "#FF69B4",
  "Inter miami": "#FF69B4",
  "River plate": "#E41B17",
  River: "#E41B17",
  "Porto FC": "#0050A4",
  "Porto fC": "#0050A4",
  "AC Milan": "#D00027", // rojo/negro
  Juventus: ["#FFFFFF", "#222222"], // blanco/negro
  Inter: ["#0074B7", "#222222"], // azul/negro (ejemplo)
  Palmeiras: "#1B9448", // verde
  Palmerias: "#1B9448", // verde (typo)
  Palmeira: "#1B9448", // verde (typo)
  "West Ham": ["#7A263A", "#FDB913"], // rojo/amarillo
  "West ham": ["#7A263A", "#FDB913"], // rojo/amarillo
  // Colores de equipos para Liga 6
  Blessed: "#1E40AF",
  Verdolagas: "#22C55E",
  "Red Devils": "#B91C1C",
  // Colores de equipos para Liga 7
  Greenworld: "#22C55E", // verde
  "DLC Team": "#222222", // negro
  "Vodka Juniors": "#2563EB", // azul
  // Colores de equipos para Liga 8
  "Ferxxo 100": "#22C55E", // verde
  "Colsafistas FC": "#2563EB", // azul
  "Junior FC": "#D00027", // rojo
  // Colores de equipos para Liga 9
  Fiorentina: "#9333EA", // morado
  Chapecoense: "#22C55E", // verde
  "Alianza FC": "#2563EB", // azul
  Bayern: "#D00027", // rojo
  Shakhtar: "#F97316", // naranja
  // Colores de equipos para Liga 10
  "Chelsea FC": "#1E40AF", // azul
  "Borussia Mönchengladbach": "#222222", // negro
  "América de Cali": "#D00027", // rojo
  "Orlando City": "#9333EA", // morado
  Holanda: "#F59E42", // naranja claro
  "Panathinaikos FC": "#22C55E", // verde
  // Colores de equipos para Liga 11
  LUSP: "#9333EA", // morado
  "Inter Milan": "#2563EB", // azul
  "All Blacks": "#222222", // negro
  Servientrega: "#22C55E", // verde
  "San Marino": "#F97316", // naranja
  // Colores de equipos para Liga 12
  "N Forest": "#D00027", // rojo
  "R Valladolid": "#9333EA", // morado
  "LA FC": "#222222", // negro
  "León FC": "#22C55E", // verde
  "Al Hilal": "#2563EB", // azul
  "H Dynamo": "#F97316", // naranja
  "Sport Boys": "#FF69B4", // Rosado
  "Celta de Vigo": "#2563EB", // verde
  "Rosario Central": "#FDB913", // naranja
  Inglaterra: "#ffffff", // negro
  Alemania: "#222222", // rojo
  // Colores de equipos para Liga PPT #14
  Brasil: "#FDB913", // amarillo
  "Equipo Rocket": "#2563EB", // azul
  "River Plate": "#FFFFFF", // blanco
  Wolverhampton: "#F97316", // naranja
  "Eintracht Frankfurt": "#222222", // negro
  "E. Frankfurt": "#222222", // negro
  Junior: "#D00027", // rojo
  "Palermo FC": "#FF69B4", // rosado
  "VfL Wolfsburgo": "#22C55E", // verde
};

// Datos de ejemplo para Liga 1
export const LIGA_1 = {
  tablaGeneral: [
    { equipo: "Boca jr", puntos: 101 },
    { equipo: "Dortmund", puntos: 86 },
    { equipo: "Real Madrid", puntos: 84 },
  ],
  jornadas: [
    {
      nombre: "Jornada 1",
      resultados: [
        { equipo: "Dortmund", puntos: 20 },
        { equipo: "Real Madrid", puntos: 18 },
        { equipo: "Boca Jrs", puntos: 16 },
      ],
    },
    {
      nombre: "Jornada 2",
      resultados: [
        { equipo: "Boca Jrs", puntos: 31 },
        { equipo: "Dortmund", puntos: 26 },
        { equipo: "Real Madrid", puntos: 21 },
      ],
    },
    {
      nombre: "Jornada 3",
      resultados: [
        { equipo: "Boca Jrs", puntos: 13 },
        { equipo: "Real madrid", puntos: 11 },
        { equipo: "Dortmund", puntos: 10 },
      ],
    },
    {
      nombre: "Jornada 4",
      resultados: [
        { equipo: "Boca Jrs", puntos: 20 },
        { equipo: "Real madrid", puntos: 15 },
        { equipo: "Dortmund", puntos: 10 },
      ],
    },
    {
      nombre: "Jornada 5",
      resultados: [
        { equipo: "Boca Jrs", puntos: 21 },
        { equipo: "Dortmund", puntos: 20 },
        { equipo: "Real Madrid", puntos: 19 },
      ],
    },
  ],
  final: "Boca 7 - Dortmund 5",
  ganador: "Boca Jrs",
};

// Datos de ejemplo para Liga 2
export const LIGA_2 = {
  tablaGeneral: [
    { equipo: "Liverpool", puntos: 160, victorias: 76, empates: 8 },
    { equipo: "Newcastle", puntos: 108, victorias: 51, empates: 6 },
    { equipo: "Manchester city", puntos: 104, victorias: 49, empates: 8 },
  ],
  jornadas: [
    {
      nombre: "Jornada 1",
      resultados: [],
      goleadores: [],
    },
    {
      nombre: "Jornada 2",
      resultados: [
        { equipo: "Manchester City", puntos: 20 },
        { equipo: "Liverpool", puntos: 23 },
        { equipo: "Newcastle", puntos: 9 },
      ],
    },
    {
      nombre: "Jornada 3",
      resultados: [
        { equipo: "Liverpool", puntos: 26, victorias: 12, empates: 2 },
        { equipo: "Manchester City", puntos: 25, victorias: 12, empates: 1 },
        { equipo: "Newcastle", puntos: 21, victorias: 10, empates: 1 },
      ],
    },
    {
      nombre: "Jornada 4",
      resultados: [
        { equipo: "Liverpool", puntos: 36 },
        { equipo: "Newcastle", puntos: 25 },
        { equipo: "Manchester City", puntos: 7 },
      ],
    },
    {
      nombre: "Jornada 5",
      resultados: [
        { equipo: "Liverpool", puntos: 30, victorias: 15, empates: 0 },
        { equipo: "Manchester City", puntos: 21, victorias: 10, empates: 1 },
        { equipo: "Newcastle", puntos: 15, victorias: 7, empates: 1 },
      ],
    },
    {
      nombre: "Jornada 6",
      resultados: [
        { equipo: "Liverpool", puntos: 23, victorias: 11, empates: 1 },
        { equipo: "Newcastle", puntos: 22, victorias: 11 },
        { equipo: "Manchester City", puntos: 9, victorias: 4, empates: 1 },
      ],
    },
  ],
  goleadoresTotales: [
    { jugador: "Emanuel Navarro", goles: 23 },
    { jugador: "Lucas Benjumea", goles: 13 },
    { jugador: "Jairo Galván", goles: 11 },
    { jugador: "Fabricio Rizo", goles: 9 },
    { jugador: "Juan de la Cruz", goles: 8 },
    { jugador: "Henry Hernandez", goles: 8 },
    { jugador: "Andres Felipe Farfán", goles: 8 },
    { jugador: "Mariano Amaris", goles: 7 },
    { jugador: "Jhonnier de la Cruz", goles: 6 },
    { jugador: "Jose Henao", goles: 5 },
    { jugador: "Cristian Benjumea", goles: 3 },
    { jugador: "Juan Mora", goles: 3 },
    { jugador: "Edward Brito", goles: 3 },
    { jugador: "Frank Ramirez", goles: 2 },
    { jugador: "Elias Lacera", goles: 2 },
    { jugador: "Moises", goles: 1 },
    { jugador: "Ronaldo", goles: 1 },
    { jugador: "Eudes Pavajeau", goles: 1 },
    { jugador: "Emanuel Celedón", goles: 1 },
    { jugador: "Monchi", goles: 1 },
    { jugador: "Camilo Laborde", goles: 1 },
    { jugador: "prens", goles: 1 },
    { jugador: "Daniel Cuadros", goles: 1 },
  ],
  goleadorLiga: { jugador: "Emanuel Navarro", goles: 23 },
  final: "Liverpool 6 - Newcastle 4",
  ganador: "Liverpool",
};

// Datos de ejemplo para Liga 3
export const LIGA_3 = {
  tablaGeneral: [
    { equipo: "Napoli", puntos: 125, victorias: 56, empates: 13 },
    { equipo: "Inter Miami", puntos: 119, victorias: 54, empates: 10 },
    { equipo: "River plate", puntos: 81, victorias: 36, empates: 7 },
  ],
  jornadas: [
    {
      nombre: "Jornada 1",
      resultados: [
        { equipo: "Napoli", puntos: 23, victorias: 10, empates: 3 },
        { equipo: "Inter Miami", puntos: 17, victorias: 7, empates: 3 },
        { equipo: "River plate", puntos: 15, victorias: 7, empates: 1 },
      ],
    },
    {
      nombre: "Jornada 2",
      resultados: [
        { equipo: "Napoli", puntos: 26, victorias: 12, empates: 2 },
        { equipo: "Inter Miami", puntos: 24, victorias: 11, empates: 2 },
        { equipo: "River", puntos: 14, victorias: 7, empates: 0 },
      ],
    },
    {
      nombre: "Jornada 3",
      resultados: [
        { equipo: "Inter miami", puntos: 26, victorias: 13, empates: 0 },
        { equipo: "Napoli", puntos: 22, victorias: 10, empates: 2 },
        { equipo: "River", puntos: 8, victorias: 3, empates: 2 },
      ],
    },
    {
      nombre: "Jornada 4",
      resultados: [
        { equipo: "River", puntos: 18, victorias: 8, empates: 2 },
        { equipo: "Napoli", puntos: 15, victorias: 6, empates: 3 },
        { equipo: "Inter miami", puntos: 15, victorias: 6, empates: 3 },
      ],
    },
    {
      nombre: "Jornada 5",
      resultados: [
        { equipo: "Inter Miami", puntos: 19, victorias: 9, empates: 1 },
        { equipo: "River", puntos: 17, victorias: 8, empates: 1 },
        { equipo: "Napoli", puntos: 16, victorias: 7, empates: 2 },
      ],
    },
    {
      nombre: "Jornada 6",
      resultados: [
        { equipo: "Napoli", puntos: 23, victorias: 11, empates: 1 },
        { equipo: "Inter Miami", puntos: 18, victorias: 8, empates: 2 },
        { equipo: "River", puntos: 9, victorias: 4, empates: 1 },
      ],
    },
  ],
  goleadoresTotales: [
    { jugador: "Emanuel Navarro", goles: 18 },
    { jugador: "Juan de la Cruz", goles: 14 },
    { jugador: "Jesus Abuchaibe", goles: 13 },
    { jugador: "Lucas Benjumea", goles: 12 },
    { jugador: "Fabricio Rizo", goles: 11 },
    { jugador: "Eudes Pavajeau", goles: 8 },
    { jugador: "Jairo Galván", goles: 8 },
    { jugador: "Henry Hernandez", goles: 7 },
    { jugador: "Ronaldo", goles: 6 },
    { jugador: "Andres Felipe Farfán", goles: 6 },
    { jugador: "Cristian Benjumea", goles: 6 },
    { jugador: "Camilo Laborde", goles: 5 },
    { jugador: "Jose Henao", goles: 5 },
    { jugador: "Mariano Amaris", goles: 4 },
    { jugador: "Emanuel Celedón", goles: 3 },
    { jugador: "Frank Ramirez", goles: 3 },
    { jugador: "Juan Mora", goles: 2 },
    { jugador: "Elias Lacera", goles: 2 },
    { jugador: "Monchi", goles: 1 },
  ],
  goleadorLiga: { jugador: "Emanuel Navarro", goles: 18 },
  arqueros: [
    { arquero: "Diego Fel", golesRecibidos: 38 },
    { arquero: "Andres Felipe", golesRecibidos: 40 },
    { arquero: "Jose Manuel", golesRecibidos: 42 },
  ],
  mejorArquero: { arquero: "Diego Fel", golesRecibidos: 38 },
  final: "Napoli 7 - Inter Miami 3",
  ganador: "Napoli",
};

// Datos de ejemplo para Liga 4
export const LIGA_4 = {
  tablaGeneral: [
    { equipo: "Porto FC", puntos: 119, victorias: 56, empates: 9 },
    { equipo: "AC Milan", puntos: 116, victorias: 52, empates: 11 },
    { equipo: "Juventus", puntos: 100, victorias: 47, empates: 11 },
  ],
  jornadas: [
    {
      nombre: "Jornada 1",
      resultados: [
        { equipo: "Juventus", puntos: 18, victorias: 8, empates: 2 },
        { equipo: "Porto FC", puntos: 10, victorias: 4, empates: 2 },
        { equipo: "AC Milan", puntos: 6, victorias: 1, empates: 4 },
      ],
    },
    {
      nombre: "Jornada 2",
      resultados: [
        { equipo: "AC Milan", puntos: 24, victorias: 11, empates: 2 },
        { equipo: "Porto FC", puntos: 16, victorias: 8, empates: 0 },
        { equipo: "Juventus", puntos: 16, victorias: 7, empates: 2 },
      ],
    },
    {
      nombre: "Jornada 3",
      resultados: [
        { equipo: "Porto FC", puntos: 24, victorias: 10, empates: 4 },
        { equipo: "AC Milan", puntos: 15, victorias: 5, empates: 5 },
        { equipo: "Juventus", puntos: 7, victorias: 2, empates: 3 },
      ],
    },
    {
      nombre: "Jornada 4",
      resultados: [
        { equipo: "AC Milan", puntos: 36, victorias: 18, empates: 0 },
        { equipo: "Juventus", puntos: 25, victorias: 12, empates: 1 },
        { equipo: "Porto FC", puntos: 19, victorias: 9, empates: 1 },
      ],
    },
    {
      nombre: "Jornada 5",
      resultados: [
        { equipo: "Juventus", puntos: 21, victorias: 10, empates: 1 },
        { equipo: "Porto FC", puntos: 21, victorias: 10, empates: 1 },
        { equipo: "AC Milan", puntos: 12, victorias: 6, empates: 0 },
      ],
    },
    {
      nombre: "Jornada 6",
      resultados: [
        { equipo: "Porto FC", puntos: 29, victorias: 14, empates: 1 },
        { equipo: "AC Milan", puntos: 23, victorias: 11, empates: 1 },
        { equipo: "Juventus", puntos: 18, victorias: 8, empates: 2 },
      ],
    },
  ],
  goleadoresTotales: [
    { jugador: "Fabricio Rizo", goles: 16 },
    { jugador: "Andres Felipe Farfán", goles: 15 },
    { jugador: "Jairo Galván", goles: 15 },
    { jugador: "Juan de la cruz", goles: 14 },
    { jugador: "Esteban Galván", goles: 10 },
    { jugador: "Lucas Benjumea", goles: 9 },
    { jugador: "Camilo Laborde", goles: 8 },
    { jugador: "Mariano Amaris A", goles: 7 },
    { jugador: "Keni Contreras", goles: 6 },
    { jugador: "Frank Ramirez", goles: 4 },
    { jugador: "Pingui", goles: 4 },
    { jugador: "Henry Hernandez", goles: 4 },
    { jugador: "Emanuel Navarro", goles: 3 },
    { jugador: "Eudes Pavajeau", goles: 3 },
    { jugador: "Daniel Cuadros", goles: 2 },
    { jugador: "Cristian Benjumea", goles: 2 },
    { jugador: "Sebastian Perez", goles: 2 },
    { jugador: "Emanuel Celedón", goles: 2 },
    { jugador: "Edward Brito", goles: 1 },
    { jugador: "Juan Mora", goles: 1 },
  ],
  goleadorLiga: { jugador: "Fabricio Rizo", goles: 16 },
  arqueros: [
    { arquero: "Diego Fel", golesRecibidos: 37 },
    { arquero: "Andres Felipe", golesRecibidos: 34 },
  ],
  mejorArquero: { arquero: "Andres Felipe", golesRecibidos: 34 },
  final: "Porto FC 9 - AC Milan 2",
  ganador: "Porto FC",
};

// Datos de ejemplo para Liga 5
export const LIGA_5 = {
  tablaGeneral: [
    { equipo: "Palmeiras", puntos: 142, victorias: 61, empates: 20 },
    { equipo: "Inter", puntos: 113, victorias: 48, empates: 15 },
    { equipo: "West Ham", puntos: 102, victorias: 41, empates: 20 },
  ],
  jornadas: [
    {
      nombre: "Jornada 1",
      resultados: [
        { equipo: "Palmeiras", puntos: 27, victorias: 12, empates: 3 },
        { equipo: "West Ham", puntos: 24, victorias: 11, empates: 2 },
        { equipo: "Inter", puntos: 21, victorias: 10, empates: 1 },
      ],
    },
    {
      nombre: "Jornada 2",
      resultados: [
        { equipo: "Palmeiras", puntos: 21, victorias: 7, empates: 7 },
        { equipo: "West Ham", puntos: 16, victorias: 5, empates: 6 },
        { equipo: "Inter", puntos: 14, victorias: 6, empates: 2 },
      ],
    },
    {
      nombre: "Jornada 3",
      resultados: [
        { equipo: "Palmerias", puntos: 24, victorias: 11, empates: 2 },
        { equipo: "Inter", puntos: 18, victorias: 8, empates: 2 },
        { equipo: "West ham", puntos: 14, victorias: 5, empates: 4 },
      ],
    },
    {
      nombre: "Jornada 4",
      resultados: [
        { equipo: "Palmeira", puntos: 28, victorias: 13, empates: 2 },
        { equipo: "Inter", puntos: 18, victorias: 8, empates: 2 },
        { equipo: "West ham", puntos: 16, victorias: 7, empates: 2 },
      ],
    },
    {
      nombre: "Jornada 5",
      resultados: [
        { equipo: "Inter", puntos: 24, victorias: 11, empates: 2 },
        { equipo: "Palmeiras", puntos: 18, victorias: 8, empates: 2 },
        { equipo: "West ham", puntos: 16, victorias: 7, empates: 2 },
      ],
    },
    {
      nombre: "Jornada 6",
      resultados: [
        { equipo: "Palmeiras", puntos: 24, victorias: 10, empates: 4 },
        { equipo: "Inter", puntos: 18, victorias: 6, empates: 6 },
        { equipo: "West ham", puntos: 16, victorias: 6, empates: 4 },
      ],
    },
  ],
  goleadoresTotales: [
    { jugador: "Pier Rizo", goles: 17 },
    { jugador: "Jurgen Hassler", goles: 14 },
    { jugador: "Andres Felipe Farfán", goles: 12 },
    { jugador: "Jefferson Almanza", goles: 11 },
    { jugador: "Juan de la Cruz", goles: 11 },
    { jugador: "Keni Contreras", goles: 11 },
    { jugador: "Emanuel Navarro", goles: 10 },
    { jugador: "Sergio Blanchar", goles: 10 },
    { jugador: "Esteban Galván", goles: 9 },
    { jugador: "Fabricio Rizo", goles: 9 },
    { jugador: "Henry Hernandez", goles: 7 },
    { jugador: "Mariano Amaris", goles: 5 },
    { jugador: "Emanuel Celedón", goles: 5 },
    { jugador: "Camilo Laborde", goles: 5 },
    { jugador: "Eudes Pavajeau", goles: 3 },
    { jugador: "Jairo Galván", goles: 3 },
    { jugador: "Lucas Benjumea", goles: 2 },
    { jugador: "Frank Ramirez", goles: 2 },
    { jugador: "Cristian Benjumea", goles: 2 },
    { jugador: "Juan Mora", goles: 1 },
  ],
  goleadorLiga: { jugador: "Pier Rizo", goles: 17 },
  arqueros: [
    { arquero: "Jose Manuel", golesRecibidos: 55 },
    { arquero: "Diego Fel", golesRecibidos: 59 },
    { arquero: "Andres Felipe Arquero", golesRecibidos: 61 },
  ],
  mejorArquero: { arquero: "Jose Manuel", golesRecibidos: 55 },
  final: "Inter 7 - Palmeiras 4",
  ganador: "Inter",
};

// Relación de arqueros por equipo para Liga 5
export const ARQUEROS_LIGA_5: Record<string, string> = {
  Palmeiras: "Jose Manuel",
  Inter: "Andres Felipe Arquero",
  "West Ham": "Diego Fel",
};

// Arqueros por equipo para Liga 6
export const ARQUEROS_LIGA_6: Record<string, string> = {
  Blessed: "Diego Fel",
  Verdolagas: "José Manuel",
  "Red Devils": "Andres Felipe",
};

// Datos de ejemplo para Liga 6
export const LIGA_6 = {
  tablaGeneral: [
    { equipo: "Blessed", puntos: 138, victorias: 62, empates: 14 },
    { equipo: "Verdolagas", puntos: 134, victorias: 60, empates: 14 },
    { equipo: "Red Devils", puntos: 105, victorias: 47, empates: 11 },
  ],
  jornadas: [
    {
      nombre: "Jornada 1",
      resultados: [
        { equipo: "Verdolagas", puntos: 24, victorias: 10, empates: 4 },
        { equipo: "Blessed", puntos: 22, victorias: 10, empates: 2 },
        { equipo: "Red Devils", puntos: 12, victorias: 5, empates: 2 },
      ],
    },
    {
      nombre: "Jornada 2",
      resultados: [
        { equipo: "Blessed", puntos: 27, victorias: 12, empates: 3 },
        { equipo: "Red Devils", puntos: 19, victorias: 7, empates: 5 },
        { equipo: "Verdolagas", puntos: 18, victorias: 8, empates: 2 },
      ],
    },
    {
      nombre: "Jornada 3",
      resultados: [
        { equipo: "Verdolagas", puntos: 28, victorias: 13, empates: 2 },
        { equipo: "Red Devils", puntos: 18, victorias: 8, empates: 2 },
        { equipo: "Blessed", puntos: 8, victorias: 3, empates: 2 },
      ],
    },
    {
      nombre: "Jornada 4",
      resultados: [
        { equipo: "Blessed", puntos: 31, victorias: 14, empates: 3 },
        { equipo: "Verdolagas", puntos: 19, victorias: 8, empates: 3 },
        { equipo: "Red Devils", puntos: 15, victorias: 7, empates: 1 },
      ],
    },
    {
      nombre: "Jornada 5",
      resultados: [
        { equipo: "Blessed", puntos: 26, victorias: 12, empates: 2 },
        { equipo: "Red Devils", puntos: 23, victorias: 11, empates: 1 },
        { equipo: "Verdolagas", puntos: 17, victorias: 8, empates: 1 },
      ],
    },
    {
      nombre: "Jornada 6",
      resultados: [
        { equipo: "Verdolagas", puntos: 28, victorias: 13, empates: 2 },
        { equipo: "Blessed", puntos: 24, victorias: 11, empates: 2 },
        { equipo: "Red Devils", puntos: 18, victorias: 9, empates: 0 },
      ],
    },
  ],
  goleadoresTotales: [
    { jugador: "Andres Felipe Farfán", goles: 22 },
    { jugador: "Jurgen Hassler", goles: 19 },
    { jugador: "Emanuel Navarro", goles: 19 },
    { jugador: "Juan de la Cruz", goles: 13 },
    { jugador: "Keni Contreras", goles: 13 },
    { jugador: "Jefferson Almanza", goles: 11 },
    { jugador: "Jairo Galván", goles: 11 },
    { jugador: "Mariano Amaris", goles: 9 },
    { jugador: "Eudes Pavajeau", goles: 8 },
    { jugador: "Emanuel Celedón", goles: 6 },
    { jugador: "Henry Hernandez", goles: 7 },
    { jugador: "Lucas Benjumea", goles: 5 },
    { jugador: "Elias Lacera", goles: 5 },
    { jugador: "Esteban Galván", goles: 4 },
    { jugador: "Camilo Laborde", goles: 4 },
    { jugador: "Sergio Blanchar", goles: 4 },
    { jugador: "Cristian Benjumea", goles: 3 },
    { jugador: "Fabricio Rizo", goles: 2 },
    { jugador: "Edward Brito", goles: 2 },
    { jugador: "Juan Mora", goles: 1 },
  ],
  goleadorLiga: { jugador: "Andres Felipe Farfán", goles: 22 },
  arqueros: [
    { arquero: "Diego Fel", golesRecibidos: 51 },
    { arquero: "José Manuel", golesRecibidos: 55 },
    { arquero: "Andres Felipe", golesRecibidos: 63 },
  ],
  mejorArquero: { arquero: "Diego Fel", golesRecibidos: 51 },
  final: "Blessed 4 - Verdolagas 6",
  ganador: "Blessed",
};

// Arqueros por equipo para Liga 7
export const ARQUEROS_LIGA_7: Record<string, string> = {
  Greenworld: "José Manuel",
  "DLC Team": "Andres Felipe arquero",
  "Vodka Juniors": "Diego Fel",
};

// Datos de ejemplo para Liga 7
export const LIGA_7 = {
  tablaGeneral: [
    { equipo: "Greenworld", puntos: 186, victorias: 85, empates: 16 },
    { equipo: "DLC Team", puntos: 87, victorias: 39, empates: 9 },
    { equipo: "Vodka Juniors", puntos: 79, victorias: 33, empates: 13 },
  ],
  jornadas: [
    {
      nombre: "Jornada 1",
      resultados: [
        { equipo: "Greenworld", puntos: 37, victorias: 18, empates: 1 },
        { equipo: "Vodka Juniors", puntos: 18, victorias: 9, empates: 0 },
        { equipo: "DLC Team", puntos: 11, victorias: 5, empates: 1 },
      ],
    },
    {
      nombre: "Jornada 2",
      resultados: [
        { equipo: "Greenworld", puntos: 27, victorias: 11, empates: 5 },
        { equipo: "DLC Team", puntos: 17, victorias: 7, empates: 3 },
        { equipo: "Vodka Juniors", puntos: 14, victorias: 5, empates: 4 },
      ],
    },
    {
      nombre: "Jornada 3",
      resultados: [
        { equipo: "Greenworld", puntos: 25, victorias: 12, empates: 1 },
        { equipo: "DLC Team", puntos: 20, victorias: 9, empates: 2 },
        { equipo: "Vodka Juniors", puntos: 7, victorias: 3, empates: 1 },
      ],
    },
    {
      nombre: "Jornada 4",
      resultados: [
        { equipo: "Greenworld", puntos: 37, victorias: 17, empates: 3 },
        { equipo: "Vodka Juniors", puntos: 13, victorias: 5, empates: 3 },
        { equipo: "DLC Team", puntos: 10, victorias: 5, empates: 0 },
      ],
    },
    {
      nombre: "Jornada 5",
      resultados: [
        { equipo: "Greenworld", puntos: 21, victorias: 9, empates: 3 },
        { equipo: "DLC Team", puntos: 15, victorias: 7, empates: 1 },
        { equipo: "Vodka Juniors", puntos: 14, victorias: 5, empates: 4 },
      ],
    },
    {
      nombre: "Jornada 6",
      resultados: [
        { equipo: "Greenworld", puntos: 39, victorias: 18, empates: 3 },
        { equipo: "DLC Team", puntos: 14, victorias: 6, empates: 2 },
        { equipo: "Vodka Juniors", puntos: 13, victorias: 6, empates: 1 },
      ],
    },
  ],
  goleadoresTotales: [
    { jugador: "Keni Contreras", goles: 23 },
    { jugador: "Emanuel Navarro", goles: 23 },
    { jugador: "Andres Felipe Farfán", goles: 18 },
    { jugador: "Frederick", goles: 17 },
    { jugador: "Jurgen Hassler", goles: 14 },
    { jugador: "Cristian Benjumea", goles: 9 },
    { jugador: "Camilo Laborde", goles: 7 },
    { jugador: "Jefferson Almanza", goles: 7 },
    { jugador: "Juan de la cruz", goles: 6 },
    { jugador: "José Viña", goles: 5 },
    { jugador: "Henry Hernandez", goles: 5 },
    { jugador: "Jairo Galván", goles: 4 },
    { jugador: "Edward Brito", goles: 3 },
    { jugador: "Sergio Blanchar", goles: 3 },
    { jugador: "Jhonnier de la Cruz", goles: 2 },
    { jugador: "Frank Ramirez", goles: 2 },
    { jugador: "Andres Felipe nuevo", goles: 2 },
    { jugador: "Mariano Amaris", goles: 2 },
    { jugador: "Fabricio Rizo", goles: 1 },
    { jugador: "Elias Lacera", goles: 1 },
    { jugador: "Lucas Benjumea", goles: 1 },
  ],
  goleadorLiga: { jugador: "Keni Contreras", goles: 23 },
  arqueros: [
    { arquero: "José Manuel", golesRecibidos: 28 },
    { arquero: "Andres Felipe arquero", golesRecibidos: 46 },
    { arquero: "Diego Fel", golesRecibidos: 47 },
  ],
  mejorArquero: { arquero: "José Manuel", golesRecibidos: 28 },
  final: "DLC Team 2 - Greenworld 11",
  ganador: "Greenworld",
};

// Arqueros por equipo para Liga 8
export const ARQUEROS_LIGA_8: Record<string, string> = {
  "Ferxxo 100": "José Manuel",
  "Colsafistas FC": "Andres Felipe arquero",
  "Junior FC": "Diego Fel",
};

// Datos de ejemplo para Liga 8
export const LIGA_8 = {
  tablaGeneral: [
    { equipo: "Colsafistas FC", puntos: 118, victorias: 50, empates: 19 },
    { equipo: "Ferxxo 100", puntos: 109, victorias: 46, empates: 17 },
    { equipo: "Junior FC", puntos: 108, victorias: 42, empates: 24 },
  ],
  jornadas: [
    {
      nombre: "Jornada 1",
      resultados: [
        { equipo: "Colsafistas FC", puntos: 30, victorias: 14, empates: 2 },
        { equipo: "Junior FC", puntos: 17, victorias: 8, empates: 1 },
        { equipo: "Ferxxo 100", puntos: 17, victorias: 8, empates: 1 },
      ],
    },
    {
      nombre: "Jornada 2",
      resultados: [
        { equipo: "Junior FC", puntos: 25, victorias: 11, empates: 3 },
        { equipo: "Colsafistas FC", puntos: 23, victorias: 10, empates: 3 },
        { equipo: "Ferxxo 100", puntos: 12, victorias: 4, empates: 4 },
      ],
    },
    {
      nombre: "Jornada 3",
      resultados: [
        { equipo: "Ferxxo 100", puntos: 19, victorias: 8, empates: 3 },
        { equipo: "Junior FC", puntos: 16, victorias: 6, empates: 4 },
        { equipo: "Colsafistas FC", puntos: 16, victorias: 7, empates: 2 },
      ],
    },
    {
      nombre: "Jornada 4",
      resultados: [
        { equipo: "Ferxxo 100", puntos: 24, victorias: 11, empates: 2 },
        { equipo: "Colsafistas FC", puntos: 19, victorias: 8, empates: 3 },
        { equipo: "Junior FC", puntos: 17, victorias: 7, empates: 3 },
      ],
    },
    {
      nombre: "Jornada 5",
      resultados: [
        { equipo: "Ferxxo 100", puntos: 19, victorias: 8, empates: 3 },
        { equipo: "Colsafistas FC", puntos: 15, victorias: 6, empates: 3 },
        { equipo: "Junior FC", puntos: 10, victorias: 2, empates: 6 },
      ],
    },
    {
      nombre: "Jornada 6",
      resultados: [
        { equipo: "Junior FC", puntos: 23, victorias: 8, empates: 7 },
        { equipo: "Ferxxo 100", puntos: 18, victorias: 7, empates: 4 },
        { equipo: "Colsafistas FC", puntos: 15, victorias: 5, empates: 5 },
      ],
    },
  ],
  goleadoresTotales: [
    { jugador: "Andres Felipe Farfán", goles: 14 },
    { jugador: "Jurgen Hassler", goles: 13 },
    { jugador: "Emanuel Navarro", goles: 12 },
    { jugador: "Keni Contreras", goles: 11 },
    { jugador: "Andres Felipe nuevo", goles: 10 },
    { jugador: "Juan de la cruz", goles: 10 },
    { jugador: "Pingüi", goles: 8 },
    { jugador: "Jesus Abuchaibe", goles: 7 },
    { jugador: "Frederick", goles: 6 },
    { jugador: "Mariano Amaris", goles: 6 },
    { jugador: "Sergio Blanchard", goles: 5 },
    { jugador: "Jefferson Almanza", goles: 5 },
    { jugador: "Eudes Pavajeau", goles: 5 },
    { jugador: "José Viña", goles: 5 },
    { jugador: "Cristian Benjumea", goles: 4 },
    { jugador: "Lucas Benjumea", goles: 4 },
    { jugador: "Emanuel Celedón", goles: 3 },
    { jugador: "Henry Hernandez", goles: 1 },
    { jugador: "Elias Lacera", goles: 1 },
    { jugador: "Juan Mora", goles: 1 },
    { jugador: "Frank Ramirez", goles: 1 },
  ],
  goleadorLiga: { jugador: "Andres Felipe Farfán", goles: 14 },

  final: "Ferxxo 100 14 - Colsafistas FC 5",
  ganador: "Ferxxo 100",
};

// Arqueros por equipo para Liga 9
export const ARQUEROS_LIGA_9: Record<string, string> = {
  Fiorentina: "Brayan Ospina",
  Juventus: "Camilo Laborde",
  Bayern: "Andres Felipe arquero",
  Shakhtar: "Juan Pablo",
  Chapecoense: "Andrés Ramírez",
  "Alianza FC": "Manuel",
};

// Datos de ejemplo para Liga 9
export const LIGA_9 = {
  tablaGeneral: [
    { equipo: "Juventus", puntos: 140, victorias: 61, empates: 18 },
    { equipo: "Fiorentina", puntos: 130, victorias: 61, empates: 8 },
    { equipo: "Chapecoense", puntos: 119, victorias: 52, empates: 15 },
    { equipo: "Alianza FC", puntos: 99, victorias: 38, empates: 23 },
    { equipo: "Bayern", puntos: 97, victorias: 38, empates: 21 },
    { equipo: "Shakhtar", puntos: 77, victorias: 31, empates: 15 },
  ],
  jornadas: [
    {
      nombre: "Jornada 1",
      resultados: [
        { equipo: "Chapecoense", puntos: 37, victorias: 18, empates: 1 },
        { equipo: "Juventus", puntos: 27, victorias: 12, empates: 3 },
        { equipo: "Bayern", puntos: 23, victorias: 11, empates: 1 },
        { equipo: "Alianza FC", puntos: 12, victorias: 4, empates: 4 },
        { equipo: "Shakhtar", puntos: 11, victorias: 4, empates: 3 },
        { equipo: "Fiorentina", puntos: 10, victorias: 5, empates: 0 },
      ],
    },
    {
      nombre: "Jornada 2",
      resultados: [
        { equipo: "Juventus", puntos: 26, victorias: 11, empates: 4 },
        { equipo: "Fiorentina", puntos: 24, victorias: 10, empates: 4 },
        { equipo: "Alianza FC", puntos: 18, victorias: 7, empates: 4 },
        { equipo: "Chapecoense", puntos: 16, victorias: 7, empates: 2 },
        { equipo: "Bayern", puntos: 11, victorias: 3, empates: 5 },
        { equipo: "Shakhtar", puntos: 7, victorias: 2, empates: 3 },
      ],
    },
    {
      nombre: "Jornada 3",
      resultados: [
        { equipo: "Fiorentina", puntos: 26, victorias: 13, empates: 0 },
        { equipo: "Chapecoense", puntos: 23, victorias: 10, empates: 3 },
        { equipo: "Bayern", puntos: 22, victorias: 9, empates: 4 },
        { equipo: "Juventus", puntos: 17, victorias: 7, empates: 3 },
        { equipo: "Alianza FC", puntos: 13, victorias: 5, empates: 3 },
        { equipo: "Shakhtar", puntos: 11, victorias: 4, empates: 3 },
      ],
    },
    {
      nombre: "Jornada 4",
      resultados: [
        { equipo: "Fiorentina", puntos: 35, victorias: 17, empates: 1 },
        { equipo: "Chapecoense", puntos: 19, victorias: 8, empates: 3 },
        { equipo: "Shakhtar", puntos: 18, victorias: 8, empates: 2 },
        { equipo: "Alianza FC", puntos: 16, victorias: 7, empates: 2 },
        { equipo: "Juventus", puntos: 13, victorias: 5, empates: 3 },
        { equipo: "Bayern", puntos: 13, victorias: 4, empates: 5 },
      ],
    },
    {
      nombre: "Jornada 5",
      resultados: [
        { equipo: "Juventus", puntos: 24, victorias: 12, empates: 0 },
        { equipo: "Alianza FC", puntos: 21, victorias: 8, empates: 5 },
        { equipo: "Bayern", puntos: 19, victorias: 9, empates: 1 },
        { equipo: "Shakhtar", puntos: 17, victorias: 8, empates: 1 },
        { equipo: "Fiorentina", puntos: 17, victorias: 8, empates: 1 },
        { equipo: "Chapecoense", puntos: 12, victorias: 4, empates: 4 },
      ],
    },
    {
      nombre: "Jornada 6",
      resultados: [
        { equipo: "Juventus", puntos: 33, victorias: 14, empates: 5 },
        { equipo: "Alianza FC", puntos: 19, victorias: 7, empates: 5 },
        { equipo: "Fiorentina", puntos: 18, victorias: 8, empates: 2 },
        { equipo: "Shakhtar", puntos: 13, victorias: 5, empates: 3 },
        { equipo: "Chapecoense", puntos: 12, victorias: 5, empates: 2 },
        { equipo: "Bayern", puntos: 9, victorias: 2, empates: 5 },
      ],
    },
  ],
  goleadoresTotales: [
    { jugador: "Jose Hernandez", goles: 25 },
    { jugador: "Keni Contreras", goles: 24 },
    { jugador: "Jurgen Hassler", goles: 21 },
    { jugador: "Jeison Santa", goles: 17 },
    { jugador: "Victor Lopez", goles: 15 },
    { jugador: "Frederick", goles: 11 },
    { jugador: "Jairo Galván", goles: 10 },
    { jugador: "Luisma", goles: 10 },
    { jugador: "Nicolas Yamal", goles: 9 },
    { jugador: "Julio", goles: 9 },
    { jugador: "Andres Felipe Farfán", goles: 9 },
    { jugador: "Juanda", goles: 8 },
    { jugador: "Cristian Benjumea", goles: 7 },
    { jugador: "Fabricio Rizo", goles: 7 },
    { jugador: "Jorge Farfán", goles: 7 },
    { jugador: "Carlos Armenta", goles: 7 },
    { jugador: "Sergio Blanchar", goles: 6 },
    { jugador: "Jefferson Almanza", goles: 6 },
    { jugador: "Juan Mora", goles: 5 },
    { jugador: "Hernan Medrano", goles: 5 },
    { jugador: "Ronald Rojas", goles: 5 },
    { jugador: "Charris", goles: 5 },
    { jugador: "Jesús Pertuz", goles: 5 },
    { jugador: "Cristian Trujillo", goles: 4 },
    { jugador: "Juan de la cruz", goles: 4 },
    { jugador: "Carlos Romero", goles: 3 },
    { jugador: "Eudes Pavajeau", goles: 3 },
    { jugador: "Junior", goles: 3 },
    { jugador: "Emanuel Celedón", goles: 3 },
    { jugador: "Nairent Rojas", goles: 3 },
    { jugador: "Omar Peralta", goles: 2 },
    { jugador: "Daniel Cuadros", goles: 2 },
    { jugador: "Luis A.", goles: 2 },
    { jugador: "Elias Lacera", goles: 2 },
    { jugador: "Kevin Pineda", goles: 5 },
    { jugador: "Frank Ramirez", goles: 2 },
    { jugador: "Jose Celedón", goles: 1 },
    { jugador: "Samuel", goles: 1 },
    { jugador: "José Viña", goles: 1 },
    { jugador: "Henry Hernandez", goles: 1 },
    { jugador: "Mariano Amaris", goles: 1 },
    { jugador: "Pingüi", goles: 1 },
    { jugador: "Andres Felipe nuevo", goles: 1 },
    { jugador: "Camilo Laborde", goles: 1 },
    { jugador: "Luis Laborde", goles: 1 },
  ],
  goleadorLiga: { jugador: "Jose Hernandez", goles: 25 },
  arqueros: [
    { arquero: "Brayan Ospina", golesRecibidos: 34 },
    { arquero: "Camilo Laborde", golesRecibidos: 39 },
    { arquero: "Andres Felipe arquero", golesRecibidos: 43 },
    { arquero: "Juan Pablo", golesRecibidos: 52 },
    { arquero: "Andrés Ramírez", golesRecibidos: 56 },
    { arquero: "Manuel", golesRecibidos: 56 },
  ],
  mejorArquero: { arquero: "Brayan Ospina", golesRecibidos: 34 },
  semifinales: ["Juventus 5 - Alianza FC 6", "Fiorentina 10 - Chapecoense 7"],
  final: "Fiorentina 9 - Alianza FC 8",
  ganador: "Fiorentina",
};

// Arqueros por equipo para Liga 10
export const ARQUEROS_LIGA_10: Record<string, string> = {
  "Chelsea FC": "Andres Felipe Arquero",
  "Borussia Mönchengladbach": "Nicolás Baute",
  "América de Cali": "Santiago Sanchez",
  "Orlando City": "Brayan Cadena",
  Holanda: "Diego Fel",
  "Panathinaikos FC": "Brayan Ospino",
};

// Datos de ejemplo para Liga 10
export const LIGA_10 = {
  tablaGeneral: [
    { equipo: "Chelsea FC", puntos: 126, victorias: 59, empates: 8 },
    {
      equipo: "Borussia Mönchengladbach",
      puntos: 118,
      victorias: 50,
      empates: 18,
    },
    { equipo: "América de Cali", puntos: 118, victorias: 49, empates: 20 },
    { equipo: "Orlando City", puntos: 105, victorias: 45, empates: 15 },
    { equipo: "Holanda", puntos: 89, victorias: 37, empates: 15 },
    { equipo: "Panathinaikos FC", puntos: 63, victorias: 26, empates: 11 },
  ],
  jornadas: [
    {
      nombre: "Jornada 1",
      resultados: [
        {
          equipo: "Borussia Mönchengladbach",
          puntos: 27,
          victorias: 11,
          empates: 5,
        },
        { equipo: "Orlando City", puntos: 24, victorias: 12, empates: 0 },
        { equipo: "América de Cali", puntos: 17, victorias: 6, empates: 5 },
        { equipo: "Holanda", puntos: 15, victorias: 7, empates: 1 },
        { equipo: "Chelsea FC", puntos: 13, victorias: 6, empates: 1 },
        { equipo: "Panathinaikos FC", puntos: 8, victorias: 2, empates: 4 },
      ],
    },
    {
      nombre: "Jornada 2",
      resultados: [
        {
          equipo: "Borussia Mönchengladbach",
          puntos: 25,
          victorias: 11,
          empates: 3,
        },
        { equipo: "Chelsea FC", puntos: 19, victorias: 8, empates: 3 },
        { equipo: "América de Cali", puntos: 19, victorias: 7, empates: 5 },
        { equipo: "Orlando City", puntos: 14, victorias: 6, empates: 2 },
        { equipo: "Panathinaikos FC", puntos: 11, victorias: 4, empates: 3 },
        { equipo: "Holanda", puntos: 4, victorias: 1, empates: 2 },
      ],
    },
    {
      nombre: "Jornada 3",
      resultados: [
        { equipo: "Orlando City", puntos: 23, victorias: 9, empates: 5 },
        { equipo: "Chelsea FC", puntos: 16, victorias: 8, empates: 0 },
        { equipo: "América de Cali", puntos: 16, victorias: 6, empates: 4 },
        { equipo: "Holanda", puntos: 15, victorias: 6, empates: 3 },
        {
          equipo: "Borussia Mönchengladbach",
          puntos: 13,
          victorias: 5,
          empates: 3,
        },
        { equipo: "Panathinaikos FC", puntos: 13, victorias: 6, empates: 1 },
      ],
    },
    {
      nombre: "Jornada 4",
      resultados: [
        { equipo: "Chelsea FC", puntos: 20, victorias: 9, empates: 2 },
        { equipo: "Holanda", puntos: 20, victorias: 9, empates: 2 },
        {
          equipo: "Borussia Mönchengladbach",
          puntos: 20,
          victorias: 8,
          empates: 4,
        },
        { equipo: "Panathinaikos FC", puntos: 15, victorias: 7, empates: 1 },
        { equipo: "América de Cali", puntos: 15, victorias: 6, empates: 3 },
        { equipo: "Orlando City", puntos: 6, victorias: 2, empates: 2 },
      ],
    },
    {
      nombre: "Jornada 5",
      resultados: [
        {
          equipo: "Borussia Mönchengladbach",
          puntos: 27,
          victorias: 13,
          empates: 1,
        },
        { equipo: "América de Cali", puntos: 22, victorias: 10, empates: 2 },
        { equipo: "Holanda", puntos: 21, victorias: 9, empates: 3 },
        { equipo: "Chelsea FC", puntos: 20, victorias: 10, empates: 0 },
        { equipo: "Orlando City", puntos: 19, victorias: 9, empates: 1 },
        { equipo: "Panathinaikos FC", puntos: 13, victorias: 6, empates: 1 },
      ],
    },
    {
      nombre: "Jornada 6",
      resultados: [
        { equipo: "Chelsea FC", puntos: 38, victorias: 18, empates: 2 },
        { equipo: "América de Cali", puntos: 29, victorias: 14, empates: 1 },
        { equipo: "Orlando City", puntos: 19, victorias: 7, empates: 5 },
        { equipo: "Holanda", puntos: 13, victorias: 5, empates: 3 },
        {
          equipo: "Borussia Mönchengladbach",
          puntos: 6,
          victorias: 2,
          empates: 2,
        },
        { equipo: "Panathinaikos FC", puntos: 3, victorias: 1, empates: 1 },
      ],
    },
  ],
  goleadoresTotales: [
    { jugador: "Jose Hernandez", goles: 31 },
    { jugador: "Jeison Santa", goles: 16 },
    { jugador: "Victor Lopez", goles: 16 },
    { jugador: "Keni Contreras", goles: 16 },
    { jugador: "Juan de la cruz", goles: 14 },
    { jugador: "Frederick", goles: 13 },
    { jugador: "Jurgen Hassler", goles: 13 },
    { jugador: "Omar Peralta", goles: 8 },
    { jugador: "Yassir", goles: 8 },
    { jugador: "Andres Felipe Farfán", goles: 8 },
    { jugador: "Julio", goles: 8 },
    { jugador: "Jairo Galván", goles: 7 },
    { jugador: "Luisma", goles: 7 },
    { jugador: "Kevin Pineda", goles: 6 },
    { jugador: "Fabricio Rizo", goles: 6 },
    { jugador: "Jesús Pertuz", goles: 5 },
    { jugador: "Juanda", goles: 4 },
    { jugador: "Cristian Benjumea", goles: 4 },
    { jugador: "Ronald Rojas", goles: 6 },
    { jugador: "Jefferson Almanza", goles: 4 },
    { jugador: "Hernan Medrano", goles: 3 },
    { jugador: "Luis V", goles: 3 },
    { jugador: "Emanuel Celedón", goles: 3 },
    { jugador: "Charris", goles: 3 },
    { jugador: "Henry Hernandez", goles: 3 },
    { jugador: "Mario", goles: 3 },
    { jugador: "Jaime", goles: 3 },
    { jugador: "Eudes Pavajeau", goles: 3 },
    { jugador: "Nicolas Yamal", goles: 3 },
    { jugador: "Trespa", goles: 3 },
    { jugador: "Daniel Cuadros", goles: 3 },
    { jugador: "Carlos Romero", goles: 3 },
    { jugador: "Carlos Armenta", goles: 3 },
    { jugador: "Jose Viña", goles: 2 },
    { jugador: "Mariano Amaris", goles: 2 },
    { jugador: "Cristian Trujillo", goles: 1 },
    { jugador: "Narent Rojas", goles: 1 },
    { jugador: "Elias Lacera", goles: 1 },
    { jugador: "Jhonnier de la Cruz", goles: 1 },
  ],
  goleadorLiga: { jugador: "Jose Hernandez", goles: 31 },
  arqueros: [
    { arquero: "Nicolás Baute", golesRecibidos: 33 },
    { arquero: "Brayan Ospino", golesRecibidos: 41 },
    { arquero: "Brayan Cadena", golesRecibidos: 44 },
    { arquero: "Andres Felipe Arquero", golesRecibidos: 48 },
    { arquero: "Santiago Sanchez", golesRecibidos: 54 },
    { arquero: "Diego Fel", golesRecibidos: 57 },
  ],
  mejorArquero: { arquero: "Nicolás Baute", golesRecibidos: 33 },
  semifinales: [
    "Chelsea FC 10 - Orlando City 11",
    "Borussia Mönchengladbach 3 - América de Cali 6",
  ],
  final: "Orlando City 7 - América de Cali 5",
  ganador: "Orlando City",
};

// Arqueros por equipo para Liga 11
export const ARQUEROS_LIGA_11: Record<string, string> = {
  Liverpool: "Brayan Cadena",
  LUSP: "Brayan Ospino",
  "Inter Milan": "Nicolas Baute",
  "All Blacks": "Andres Felipe Arquero",
  Servientrega: "Santiago Sanchez",
  "San Marino": "Luis Ángel",
};

// Datos de ejemplo para Liga 11
export const LIGA_11 = {
  tablaGeneral: [
    { equipo: "Liverpool", puntos: 138, victorias: 60, empates: 18 },
    { equipo: "LUSP", puntos: 128, victorias: 51, empates: 26 },
    { equipo: "Inter Milan", puntos: 112, victorias: 47, empates: 18 },
    { equipo: "All Blacks", puntos: 102, victorias: 42, empates: 18 },
    { equipo: "Servientrega", puntos: 86, victorias: 29, empates: 28 },
    { equipo: "San Marino", puntos: 69, victorias: 26, empates: 17 },
  ],
  jornadas: [
    {
      nombre: "Jornada 1",
      resultados: [
        { equipo: "LUSP", puntos: 26, victorias: 12, empates: 2 },
        { equipo: "Liverpool", puntos: 26, victorias: 11, empates: 4 },
        { equipo: "Servientrega", puntos: 21, victorias: 8, empates: 5 },
        { equipo: "All Blacks", puntos: 14, victorias: 6, empates: 2 },
        { equipo: "Inter Milan", puntos: 14, victorias: 6, empates: 2 },
        { equipo: "San Marino", puntos: 5, victorias: 1, empates: 3 },
      ],
    },
    {
      nombre: "Jornada 2",
      resultados: [
        { equipo: "Liverpool", puntos: 25, victorias: 11, empates: 3 },
        { equipo: "Inter Milan", puntos: 21, victorias: 9, empates: 3 },
        { equipo: "All Blacks", puntos: 20, victorias: 7, empates: 6 },
        { equipo: "LUSP", puntos: 12, victorias: 5, empates: 2 },
        { equipo: "San Marino", puntos: 12, victorias: 4, empates: 4 },
        { equipo: "Servientrega", puntos: 9, victorias: 2, empates: 5 },
      ],
    },
    {
      nombre: "Jornada 3",
      resultados: [
        { equipo: "Liverpool", puntos: 22, victorias: 9, empates: 4 },
        { equipo: "Inter Milan", puntos: 22, victorias: 9, empates: 4 },
        { equipo: "LUSP", puntos: 17, victorias: 7, empates: 3 },
        { equipo: "Servientrega", puntos: 13, victorias: 5, empates: 3 },
        { equipo: "All Blacks", puntos: 12, victorias: 5, empates: 2 },
        { equipo: "San Marino", puntos: 12, victorias: 4, empates: 4 },
      ],
    },
    {
      nombre: "Jornada 4",
      resultados: [
        { equipo: "Inter Milan", puntos: 24, victorias: 11, empates: 2 },
        { equipo: "All Blacks", puntos: 22, victorias: 10, empates: 2 },
        { equipo: "San Marino", puntos: 18, victorias: 9, empates: 0 },
        { equipo: "LUSP", puntos: 18, victorias: 6, empates: 6 },
        { equipo: "Liverpool", puntos: 16, victorias: 7, empates: 2 },
        { equipo: "Servientrega", puntos: 14, victorias: 4, empates: 6 },
      ],
    },
    {
      nombre: "Jornada 5",
      resultados: [
        { equipo: "Liverpool", puntos: 33, victorias: 15, empates: 3 },
        { equipo: "LUSP", puntos: 26, victorias: 10, empates: 6 },
        { equipo: "All Blacks", puntos: 20, victorias: 9, empates: 2 },
        { equipo: "San Marino", puntos: 13, victorias: 5, empates: 3 },
        { equipo: "Inter Milan", puntos: 12, victorias: 4, empates: 4 },
        { equipo: "Servientrega", puntos: 12, victorias: 4, empates: 4 },
      ],
    },
    {
      nombre: "Jornada 6",
      resultados: [
        { equipo: "LUSP", puntos: 29, victorias: 11, empates: 7 },
        { equipo: "Inter Milan", puntos: 19, victorias: 8, empates: 3 },
        { equipo: "Servientrega", puntos: 17, victorias: 6, empates: 5 },
        { equipo: "Liverpool", puntos: 16, victorias: 7, empates: 2 },
        { equipo: "All Blacks", puntos: 14, victorias: 5, empates: 4 },
        { equipo: "San Marino", puntos: 9, victorias: 3, empates: 3 },
      ],
    },
  ],
  goleadoresTotales: [
    { jugador: "Jose Hernandez", goles: 26 },
    { jugador: "Victor Lopez L", goles: 16 },
    { jugador: "Jurgen Hassler", goles: 14 },
    { jugador: "Jeison Santa", goles: 13 },
    { jugador: "Mario Orozco", goles: 11 },
    { jugador: "Victor Lopez C", goles: 11 },
    { jugador: "Keni Contreras Contreras", goles: 11 },
    { jugador: "Pingui", goles: 10 },
    { jugador: "Andres Felipe Farfán", goles: 10 },
    { jugador: "Santiago Corzo", goles: 8 },
    { jugador: "Carlos Armenta", goles: 8 },
    { jugador: "Ronald Rojas", goles: 8 },
    { jugador: "Henry Hernandez", goles: 7 },
    { jugador: "Mariano Amaris", goles: 7 },
    { jugador: "Jairo Galván", goles: 7 },
    { jugador: "Cristian Trujillo", goles: 5 },
    { jugador: "Juan de la cruz", goles: 5 },
    { jugador: "Fabricio Rizo", goles: 5 },
    { jugador: "Carlos Romero", goles: 5 },
    { jugador: "Juan Sebastian", goles: 4 },
    { jugador: "Esteban Galván", goles: 4 },
    { jugador: "Yassir", goles: 4 },
    { jugador: "Jose Viña", goles: 4 },
    { jugador: "Jefferson Almanza", goles: 4 },
    { jugador: "Omar Peralta", goles: 3 },
    { jugador: "Andres Felipe nuevo", goles: 3 },
    { jugador: "Emanuel Celedón", goles: 3 },
    { jugador: "Frank Ramirez", goles: 3 },
    { jugador: "Charris", goles: 3 },
    { jugador: "Elias Lacera", goles: 3 },
    { jugador: "Hernan Medrano", goles: 3 },
    { jugador: "Kevin Pineda", goles: 2 },
    { jugador: "Narent Rojas", goles: 2 },
    { jugador: "Eudes Pavajeau", goles: 2 },
    { jugador: "Santiago Sanchez", goles: 2 },
    { jugador: "Cristian Benjumea", goles: 2 },
    { jugador: "Nicolas Yamal", goles: 1 },
    { jugador: "Frederick", goles: 1 },
    { jugador: "Sergio Blanchar", goles: 1 },
    { jugador: "Hernan Medrano", goles: 1 },
    { jugador: "Jesús Pertuz", goles: 1 },
    { jugador: "Daniel Cuadros", goles: 1 },
    { jugador: "Brayan ospino", goles: 1 },
  ],
  goleadorLiga: { jugador: "Jose Hernandez", goles: 26 },
  arqueros: [
    { arquero: "Brayan Ospino", golesRecibidos: 29 },
    { arquero: "Brayan Cadena", golesRecibidos: 38 },
    { arquero: "Santiago Sanchez", golesRecibidos: 42 },
    { arquero: "Nicolas Baute", golesRecibidos: 43 },
    { arquero: "Andres Felipe Arquero", golesRecibidos: 50 },
    { arquero: "Luis Ángel", golesRecibidos: 53 },
  ],
  mejorArquero: { arquero: "Brayan Ospino", golesRecibidos: 29 },
  semifinales: ["Liverpool 11 - All Blacks 9", "LUSP 5 - Inter Milan 1"],
  final: "LUSP 9 - Liverpool 5",
  ganador: "LUSP",
};

// Arqueros por equipo para Liga 12
export const ARQUEROS_LIGA_12: Record<string, string> = {
  "N Forest": "Jean Carlos",
  "R Valladolid": "Santiago Sanchez",
  "LA FC": "Camilo Laborde",
  "León FC": "Leonardo Orozco",
  "Al Hilal": "Brayan Ospina",
  "H Dynamo": "Andres Felipe",
};

// Datos de ejemplo para Liga 12
export const LIGA_12 = {
  tablaGeneral: [
    {
      equipo: "N Forest",
      puntos: 125,
      victorias: 59,
      empates: 9,
      derrotas: 0,
      pj: 68,
      porcentajeVictorias: 86.8,
    },
    {
      equipo: "R Valladolid",
      puntos: 124,
      victorias: 54,
      empates: 16,
      derrotas: 0,
      pj: 70,
      porcentajeVictorias: 77.1,
    },
    {
      equipo: "LA FC",
      puntos: 123,
      victorias: 54,
      empates: 15,
      derrotas: 0,
      pj: 69,
      porcentajeVictorias: 78.3,
    },
    {
      equipo: "León FC",
      puntos: 120,
      victorias: 53,
      empates: 14,
      derrotas: 0,
      pj: 67,
      porcentajeVictorias: 79.1,
    },
    {
      equipo: "Al Hilal",
      puntos: 117,
      victorias: 51,
      empates: 15,
      derrotas: 0,
      pj: 66,
      porcentajeVictorias: 77.3,
    },
    {
      equipo: "H Dynamo",
      puntos: 82,
      victorias: 35,
      empates: 12,
      derrotas: 0,
      pj: 47,
      porcentajeVictorias: 74.5,
    },
  ],
  jornadas: [
    {
      nombre: "Jornada 1",
      resultados: [
        {
          equipo: "N Forest",
          pj: 13,
          v: 12,
          e: 1,
          d: 0,
          puntos: 25,
          porcentajeVictorias: 92.3,
        },
        {
          equipo: "León FC",
          pj: 10,
          v: 8,
          e: 2,
          d: 0,
          puntos: 18,
          porcentajeVictorias: 80.0,
        },
        {
          equipo: "R Valladolid",
          pj: 11,
          v: 7,
          e: 4,
          d: 0,
          puntos: 18,
          porcentajeVictorias: 63.6,
        },
        {
          equipo: "Al Hilal",
          pj: 9,
          v: 8,
          e: 1,
          d: 0,
          puntos: 17,
          porcentajeVictorias: 88.9,
        },
        {
          equipo: "LA FC",
          pj: 10,
          v: 7,
          e: 3,
          d: 0,
          puntos: 17,
          porcentajeVictorias: 70.0,
        },
        {
          equipo: "H Dynamo",
          pj: 7,
          v: 4,
          e: 3,
          d: 0,
          puntos: 11,
          porcentajeVictorias: 57.1,
        },
      ],
    },
    {
      nombre: "Jornada 2",
      resultados: [
        {
          equipo: "R Valladolid",
          pj: 18,
          v: 16,
          e: 2,
          d: 0,
          puntos: 34,
          porcentajeVictorias: 88.9,
        },
        {
          equipo: "León FC",
          pj: 11,
          v: 9,
          e: 2,
          d: 0,
          puntos: 20,
          porcentajeVictorias: 81.8,
        },
        {
          equipo: "H Dynamo",
          pj: 10,
          v: 9,
          e: 1,
          d: 0,
          puntos: 19,
          porcentajeVictorias: 90.0,
        },
        {
          equipo: "Al Hilal",
          pj: 9,
          v: 8,
          e: 1,
          d: 0,
          puntos: 17,
          porcentajeVictorias: 88.9,
        },
        {
          equipo: "LA FC",
          pj: 10,
          v: 7,
          e: 3,
          d: 0,
          puntos: 17,
          porcentajeVictorias: 70.0,
        },
        {
          equipo: "N Forest",
          pj: 8,
          v: 7,
          e: 1,
          d: 0,
          puntos: 15,
          porcentajeVictorias: 87.5,
        },
      ],
    },
    {
      nombre: "Jornada 3",
      resultados: [
        {
          equipo: "León FC",
          pj: 14,
          v: 12,
          e: 2,
          d: 0,
          puntos: 26,
          porcentajeVictorias: 85.7,
        },
        {
          equipo: "H Dynamo",
          pj: 13,
          v: 12,
          e: 1,
          d: 0,
          puntos: 25,
          porcentajeVictorias: 92.3,
        },
        {
          equipo: "LA FC",
          pj: 12,
          v: 9,
          e: 3,
          d: 0,
          puntos: 21,
          porcentajeVictorias: 75.0,
        },
        {
          equipo: "Al Hilal",
          pj: 10,
          v: 8,
          e: 2,
          d: 0,
          puntos: 18,
          porcentajeVictorias: 80.0,
        },
        {
          equipo: "N Forest",
          pj: 10,
          v: 7,
          e: 3,
          d: 0,
          puntos: 17,
          porcentajeVictorias: 70.0,
        },
        {
          equipo: "R Valladolid",
          pj: 10,
          v: 7,
          e: 3,
          d: 0,
          puntos: 17,
          porcentajeVictorias: 70.0,
        },
      ],
    },
    {
      nombre: "Jornada 4",
      resultados: [
        {
          equipo: "N Forest",
          pj: 18,
          v: 17,
          e: 1,
          d: 0,
          puntos: 35,
          porcentajeVictorias: 94.4,
        },
        {
          equipo: "Al Hilal",
          pj: 16,
          v: 11,
          e: 5,
          d: 0,
          puntos: 27,
          porcentajeVictorias: 68.8,
        },
        {
          equipo: "LA FC",
          pj: 12,
          v: 11,
          e: 1,
          d: 0,
          puntos: 23,
          porcentajeVictorias: 91.7,
        },
        {
          equipo: "León FC",
          pj: 10,
          v: 5,
          e: 5,
          d: 0,
          puntos: 15,
          porcentajeVictorias: 50.0,
        },
        {
          equipo: "R Valladolid",
          pj: 6,
          v: 4,
          e: 2,
          d: 0,
          puntos: 10,
          porcentajeVictorias: 66.7,
        },
        {
          equipo: "H Dynamo",
          pj: 5,
          v: 3,
          e: 2,
          d: 0,
          puntos: 8,
          porcentajeVictorias: 60.0,
        },
      ],
    },
    {
      nombre: "Jornada 5",
      resultados: [
        {
          equipo: "LA FC",
          pj: 15,
          v: 12,
          e: 3,
          d: 0,
          puntos: 27,
          porcentajeVictorias: 80.0,
        },
        {
          equipo: "Al Hilal",
          pj: 14,
          v: 11,
          e: 3,
          d: 0,
          puntos: 25,
          porcentajeVictorias: 78.6,
        },
        {
          equipo: "León FC",
          pj: 12,
          v: 11,
          e: 1,
          d: 0,
          puntos: 23,
          porcentajeVictorias: 91.7,
        },
        {
          equipo: "R Valladolid",
          pj: 11,
          v: 10,
          e: 1,
          d: 0,
          puntos: 21,
          porcentajeVictorias: 90.9,
        },
        {
          equipo: "N Forest",
          pj: 9,
          v: 9,
          e: 0,
          d: 0,
          puntos: 18,
          porcentajeVictorias: 100.0,
        },
        {
          equipo: "H Dynamo",
          pj: 4,
          v: 3,
          e: 1,
          d: 0,
          puntos: 7,
          porcentajeVictorias: 75.0,
        },
      ],
    },
    {
      nombre: "Jornada 6",
      resultados: [
        {
          equipo: "R Valladolid",
          pj: 14,
          v: 10,
          e: 4,
          d: 0,
          puntos: 24,
          porcentajeVictorias: 71.4,
        },
        {
          equipo: "León FC",
          pj: 10,
          v: 8,
          e: 2,
          d: 0,
          puntos: 18,
          porcentajeVictorias: 80.0,
        },
        {
          equipo: "LA FC",
          pj: 10,
          v: 8,
          e: 2,
          d: 0,
          puntos: 18,
          porcentajeVictorias: 80.0,
        },
        {
          equipo: "N Forest",
          pj: 9,
          v: 6,
          e: 3,
          d: 0,
          puntos: 15,
          porcentajeVictorias: 66.7,
        },
        {
          equipo: "Al Hilal",
          pj: 8,
          v: 5,
          e: 3,
          d: 0,
          puntos: 13,
          porcentajeVictorias: 62.5,
        },
        {
          equipo: "H Dynamo",
          pj: 8,
          v: 4,
          e: 4,
          d: 0,
          puntos: 12,
          porcentajeVictorias: 50.0,
        },
      ],
    },
  ],
  goleadoresTotales: [
    { jugador: "Jurgen Hassler", goles: 28 },
    { jugador: "José Hernández", goles: 24 },
    { jugador: "Santiago Corzo", goles: 16 },
    { jugador: "Andres Felipe Farfán", goles: 16 },
    { jugador: "Jairo Galván", goles: 15 },
    { jugador: "Ronald Rojas", goles: 14 },
    { jugador: "Toto", goles: 13 },
    { jugador: "Mario Orozco", goles: 12 },
    { jugador: "Jeison Santa", goles: 11 },
    { jugador: "Juan de la Cruz", goles: 10 },
    { jugador: "Carlos Armenta", goles: 10 },
    { jugador: "Juan Dybala", goles: 9 },
    { jugador: "Fabricio Rizo", goles: 9 },
    { jugador: "Pingui", goles: 8 },
    { jugador: "Esteban Galván", goles: 8 },
    { jugador: "Hernan Medrano", goles: 7 },
    { jugador: "Jefferson Almanza", goles: 7 },
    { jugador: "Nicolas Yamal", goles: 7 },
    { jugador: "Cristian Trujillo", goles: 7 },
    { jugador: "Victor Lopez", goles: 6 },
    { jugador: "Cristian Benjumea", goles: 6 },
    { jugador: "Emanuel Celedón", goles: 6 },
    { jugador: "Yassir", goles: 6 },
    { jugador: "Carlos Romero", goles: 6 },
    { jugador: "Jose Viña", goles: 5 },
    { jugador: "Keni Contreras", goles: 5 },
    { jugador: "Jhonnier de la Cruz", goles: 4 },
    { jugador: "Kevin Pineda", goles: 4 },
    { jugador: "Jesús Pertuz", goles: 3 },
    { jugador: "Mariano Amaris", goles: 3 },
    { jugador: "Elias Lacera", goles: 2 },
    { jugador: "Frederick", goles: 2 },
    { jugador: "Narent Rojas", goles: 2 },
    { jugador: "Breiner Corzo", goles: 2 },
    { jugador: "Victor Cantillo", goles: 2 },
    { jugador: "Charris", goles: 1 },
    { jugador: "Eudes Pavajeau", goles: 1 },
    { jugador: "Oscar Perez", goles: 1 },
    { jugador: "Sergio Blanchar", goles: 1 },
    { jugador: "Edward Brito", goles: 1 },
  ],
  goleadorLiga: { jugador: "Jurgen Hassler H", goles: 28 },
  arqueros: [
    { arquero: "Brayan Ospina", golesRecibidos: 46 },
    { arquero: "Camilo Laborde", golesRecibidos: 48 },
    { arquero: "Leonardo Orozco", golesRecibidos: 49 },
    { arquero: "Santiago Sanchez", golesRecibidos: 49 },
    { arquero: "Jean Carlos", golesRecibidos: 53 },
    { arquero: "Andres Felipe", golesRecibidos: 56 },
  ],
  mejorArquero: { arquero: "Brayan Ospina", golesRecibidos: 46 },
  semifinales: ["N Forest 4 - León FC 6", "R Valladolid 5 - LA FC 3"],
  final: "R Valladolid 11 - León FC 4",
  ganador: "R Valladolid",
};

// Arqueros por equipo para Liga 13
export const ARQUEROS_LIGA_13: Record<string, string> = {
  "Sport Boys": "Brayan Cadena",
  Alemania: "Leonardo Cadena",
  Holanda: "Fernando Gómez",
  "Celta de Vigo": "Santiago Sánchez",
  Inglaterra: "Brayan Ospino",
  "AC Milan": "Camilo Laborde",
  "Rosario Central": "Carlos Barraza",
  Fiorentina: "Jorge Cotes",
  Palmeiras: "Pipe Castillejo",
};

// Datos de ejemplo para Liga 13
export const LIGA_13 = {
  tablaGeneral: [
    {
      equipo: "Sport Boys",
      pj: 122,
      victorias: 67,
      empates: 16,
      derrotas: 39,
      porcentajeVictorias: 55,
      puntos: 150,
    },
    {
      equipo: "Holanda",
      pj: 112,
      victorias: 56,
      empates: 15,
      derrotas: 41,
      porcentajeVictorias: 50,
      puntos: 127,
    },
    {
      equipo: "Fiorentina",
      pj: 127,
      victorias: 57,
      empates: 11,
      derrotas: 59,
      porcentajeVictorias: 45,
      puntos: 125,
    },
    {
      equipo: "Inglaterra",
      pj: 114,
      victorias: 53,
      empates: 17,
      derrotas: 44,
      porcentajeVictorias: 46,
      puntos: 123,
    },
    {
      equipo: "Alemania",
      pj: 106,
      victorias: 49,
      empates: 17,
      derrotas: 40,
      porcentajeVictorias: 46,
      puntos: 115,
    },
    {
      equipo: "Celta de Vigo",
      pj: 99,
      victorias: 41,
      empates: 16,
      derrotas: 42,
      porcentajeVictorias: 41,
      puntos: 98,
    },
    {
      equipo: "AC Milan",
      pj: 101,
      victorias: 41,
      empates: 15,
      derrotas: 45,
      porcentajeVictorias: 41,
      puntos: 97,
    },
    {
      equipo: "Rosario Central",
      pj: 99,
      victorias: 34,
      empates: 13,
      derrotas: 52,
      porcentajeVictorias: 34,
      puntos: 81,
    },
    {
      equipo: "Palmeiras",
      pj: 111,
      victorias: 36,
      empates: 6,
      derrotas: 69,
      porcentajeVictorias: 32,
      puntos: 78,
    },
  ],
  jornadas: [
    {
      nombre: "Jornada 1",
      resultados: [
        {
          equipo: "Holanda",
          pj: 20,
          v: 11,
          e: 2,
          d: 7,
          puntos: 24,
          porcentajeVictorias: 55,
        },
        {
          equipo: "Inglaterra",
          pj: 19,
          v: 9,
          e: 5,
          d: 5,
          puntos: 23,
          porcentajeVictorias: 47,
        },
        {
          equipo: "Celta de Vigo",
          pj: 17,
          v: 7,
          e: 4,
          d: 6,
          puntos: 18,
          porcentajeVictorias: 41,
        },
        {
          equipo: "Fiorentina",
          pj: 20,
          v: 8,
          e: 2,
          d: 10,
          puntos: 18,
          porcentajeVictorias: 40,
        },
        {
          equipo: "Sport Boys",
          pj: 20,
          v: 8,
          e: 2,
          d: 10,
          puntos: 18,
          porcentajeVictorias: 40,
        },
        {
          equipo: "Alemania",
          pj: 12,
          v: 5,
          e: 3,
          d: 4,
          puntos: 13,
          porcentajeVictorias: 42,
        },
        {
          equipo: "AC Milan",
          pj: 12,
          v: 5,
          e: 2,
          d: 5,
          puntos: 12,
          porcentajeVictorias: 42,
        },
        {
          equipo: "Rosario Central",
          pj: 12,
          v: 4,
          e: 3,
          d: 5,
          puntos: 11,
          porcentajeVictorias: 33,
        },
        {
          equipo: "Palmeiras",
          pj: 14,
          v: 4,
          e: 1,
          d: 9,
          puntos: 9,
          porcentajeVictorias: 29,
        },
      ],
    },
    {
      nombre: "Jornada 2",
      resultados: [
        {
          equipo: "Holanda",
          pj: 26,
          v: 15,
          e: 1,
          d: 10,
          puntos: 31,
          porcentajeVictorias: 58,
        },
        {
          equipo: "Palmeiras",
          pj: 26,
          v: 14,
          e: 2,
          d: 10,
          puntos: 30,
          porcentajeVictorias: 54,
        },
        {
          equipo: "Sport Boys",
          pj: 21,
          v: 10,
          e: 4,
          d: 7,
          puntos: 24,
          porcentajeVictorias: 48,
        },
        {
          equipo: "Fiorentina",
          pj: 19,
          v: 9,
          e: 3,
          d: 7,
          puntos: 21,
          porcentajeVictorias: 47,
        },
        {
          equipo: "Alemania",
          pj: 18,
          v: 8,
          e: 5,
          d: 5,
          puntos: 21,
          porcentajeVictorias: 44,
        },
        {
          equipo: "Inglaterra",
          pj: 19,
          v: 9,
          e: 2,
          d: 8,
          puntos: 20,
          porcentajeVictorias: 47,
        },
        {
          equipo: "Rosario Central",
          pj: 22,
          v: 6,
          e: 1,
          d: 15,
          puntos: 13,
          porcentajeVictorias: 27,
        },
        {
          equipo: "AC Milan",
          pj: 16,
          v: 5,
          e: 2,
          d: 9,
          puntos: 12,
          porcentajeVictorias: 31,
        },
        {
          equipo: "Celta de Vigo",
          pj: 17,
          v: 4,
          e: 4,
          d: 9,
          puntos: 12,
          porcentajeVictorias: 24,
        },
      ],
    },
    {
      nombre: "Jornada 3",
      resultados: [
        {
          equipo: "Sport Boys",
          pj: 21,
          v: 15,
          e: 3,
          d: 3,
          puntos: 33,
          porcentajeVictorias: 71,
        },
        {
          equipo: "Inglaterra",
          pj: 21,
          v: 10,
          e: 2,
          d: 9,
          puntos: 22,
          porcentajeVictorias: 48,
        },
        {
          equipo: "Holanda",
          pj: 18,
          v: 9,
          e: 3,
          d: 6,
          puntos: 21,
          porcentajeVictorias: 50,
        },
        {
          equipo: "Alemania",
          pj: 20,
          v: 9,
          e: 2,
          d: 9,
          puntos: 20,
          porcentajeVictorias: 45,
        },
        {
          equipo: "Fiorentina",
          pj: 21,
          v: 9,
          e: 2,
          d: 10,
          puntos: 20,
          porcentajeVictorias: 43,
        },
        {
          equipo: "Celta de Vigo",
          pj: 17,
          v: 8,
          e: 1,
          d: 8,
          puntos: 17,
          porcentajeVictorias: 47,
        },
        {
          equipo: "Rosario Central",
          pj: 16,
          v: 6,
          e: 1,
          d: 9,
          puntos: 13,
          porcentajeVictorias: 38,
        },
        {
          equipo: "AC Milan",
          pj: 15,
          v: 5,
          e: 2,
          d: 8,
          puntos: 12,
          porcentajeVictorias: 33,
        },
        {
          equipo: "Palmeiras",
          pj: 15,
          v: 2,
          e: 2,
          d: 11,
          puntos: 6,
          porcentajeVictorias: 13,
        },
      ],
    },
    {
      nombre: "Jornada 4",
      resultados: [
        {
          equipo: "AC Milan",
          pj: 26,
          v: 14,
          e: 1,
          d: 11,
          puntos: 29,
          porcentajeVictorias: 54,
        },
        {
          equipo: "Fiorentina",
          pj: 27,
          v: 14,
          e: 1,
          d: 12,
          puntos: 29,
          porcentajeVictorias: 52,
        },
        {
          equipo: "Sport Boys",
          pj: 18,
          v: 11,
          e: 4,
          d: 3,
          puntos: 26,
          porcentajeVictorias: 61,
        },
        {
          equipo: "Holanda",
          pj: 13,
          v: 7,
          e: 4,
          d: 2,
          puntos: 18,
          porcentajeVictorias: 54,
        },
        {
          equipo: "Palmeiras",
          pj: 21,
          v: 9,
          e: 0,
          d: 12,
          puntos: 18,
          porcentajeVictorias: 43,
        },
        {
          equipo: "Alemania",
          pj: 13,
          v: 4,
          e: 4,
          d: 5,
          puntos: 12,
          porcentajeVictorias: 31,
        },
        {
          equipo: "Rosario Central",
          pj: 13,
          v: 3,
          e: 5,
          d: 5,
          puntos: 11,
          porcentajeVictorias: 23,
        },
        {
          equipo: "Inglaterra",
          pj: 12,
          v: 3,
          e: 2,
          d: 7,
          puntos: 8,
          porcentajeVictorias: 25,
        },
        {
          equipo: "Celta de Vigo",
          pj: 13,
          v: 3,
          e: 1,
          d: 9,
          puntos: 7,
          porcentajeVictorias: 23,
        },
      ],
    },
    {
      nombre: "Jornada 5",
      resultados: [
        {
          equipo: "Sport Boys",
          pj: 26,
          v: 16,
          e: 1,
          d: 9,
          puntos: 33,
          porcentajeVictorias: 62,
        },
        {
          equipo: "Fiorentina",
          pj: 24,
          v: 13,
          e: 2,
          d: 9,
          puntos: 28,
          porcentajeVictorias: 54,
        },
        {
          equipo: "Alemania",
          pj: 25,
          v: 13,
          e: 2,
          d: 10,
          puntos: 28,
          porcentajeVictorias: 52,
        },
        {
          equipo: "AC Milan",
          pj: 16,
          v: 7,
          e: 5,
          d: 4,
          puntos: 19,
          porcentajeVictorias: 44,
        },
        {
          equipo: "Inglaterra",
          pj: 20,
          v: 8,
          e: 3,
          d: 9,
          puntos: 19,
          porcentajeVictorias: 40,
        },
        {
          equipo: "Celta de Vigo",
          pj: 14,
          v: 6,
          e: 3,
          d: 5,
          puntos: 15,
          porcentajeVictorias: 43,
        },
        {
          equipo: "Rosario Central",
          pj: 18,
          v: 7,
          e: 1,
          d: 10,
          puntos: 15,
          porcentajeVictorias: 39,
        },
        {
          equipo: "Holanda",
          pj: 14,
          v: 4,
          e: 2,
          d: 8,
          puntos: 10,
          porcentajeVictorias: 29,
        },
        {
          equipo: "Palmeiras",
          pj: 19,
          v: 4,
          e: 1,
          d: 14,
          puntos: 9,
          porcentajeVictorias: 21,
        },
      ],
    },
    {
      nombre: "Jornada 6",
      resultados: [
        {
          equipo: "Inglaterra",
          pj: 23,
          v: 14,
          e: 3,
          d: 6,
          puntos: 31,
          porcentajeVictorias: 61,
        },
        {
          equipo: "Celta de Vigo",
          pj: 21,
          v: 13,
          e: 3,
          d: 5,
          puntos: 29,
          porcentajeVictorias: 62,
        },
        {
          equipo: "Holanda",
          pj: 21,
          v: 10,
          e: 3,
          d: 8,
          puntos: 23,
          porcentajeVictorias: 48,
        },
        {
          equipo: "Alemania",
          pj: 18,
          v: 10,
          e: 1,
          d: 7,
          puntos: 21,
          porcentajeVictorias: 56,
        },
        {
          equipo: "Rosario Central",
          pj: 18,
          v: 8,
          e: 2,
          d: 8,
          puntos: 18,
          porcentajeVictorias: 44,
        },
        {
          equipo: "Sport Boys",
          pj: 18,
          v: 7,
          e: 4,
          d: 7,
          puntos: 18,
          porcentajeVictorias: 39,
        },
        {
          equipo: "AC Milan",
          pj: 16,
          v: 5,
          e: 3,
          d: 8,
          puntos: 13,
          porcentajeVictorias: 31,
        },
        {
          equipo: "Fiorentina",
          pj: 16,
          v: 4,
          e: 1,
          d: 11,
          puntos: 9,
          porcentajeVictorias: 25,
        },
        {
          equipo: "Palmeiras",
          pj: 16,
          v: 3,
          e: 0,
          d: 13,
          puntos: 6,
          porcentajeVictorias: 19,
        },
      ],
    },
  ],
  goleadoresTotales: [
    { jugador: "José Hernández", goles: 29 },
    { jugador: "Jürgen Hassler", goles: 21 },
    { jugador: "Mario Orozco", goles: 18 },
    { jugador: "Juan DLC", goles: 17 },
    { jugador: "Yassir Fuentes", goles: 16 },
    { jugador: "Keni Contreras", goles: 14 },
    { jugador: "Sergio Barrera", goles: 14 },
    { jugador: "Keiler Fonseca", goles: 14 },
    { jugador: "Julio Ochoa", goles: 14 },
    { jugador: "Jefferson Almanza", goles: 14 },
    { jugador: "Andy Córdoba (Pingui)", goles: 13 },
    { jugador: "Emanuel Navarro (Goat)", goles: 11 },
    { jugador: "Santiago Corzo", goles: 11 },
    { jugador: "José Mosquera", goles: 11 },
    { jugador: "Camilo Torres", goles: 10 },
    { jugador: "Nico Yamal", goles: 9 },
    { jugador: "Jairo Galván", goles: 9 },
    { jugador: "Dairo Martínez", goles: 9 },
    { jugador: "Carlos Armenta", goles: 8 },
    { jugador: "Andrés Farfán", goles: 8 },
    { jugador: "José Viña", goles: 8 },
    { jugador: "Arnold Castillo", goles: 8 },
    { jugador: "Cristian Trujillo", goles: 7 },
    { jugador: "Luis Rico", goles: 7 },
    { jugador: "Fabricio Rizo", goles: 6 },
    { jugador: "Hernán Medrano", goles: 6 },
    { jugador: "Edward Brito (Titi)", goles: 6 },
    { jugador: "Daniel Cuadros", goles: 6 },
    { jugador: "Jefferson Medrano", goles: 6 },
    { jugador: "Esteban Galván", goles: 6 },
    { jugador: "Juan Dybala", goles: 5 },
    { jugador: "Kevin Pineda", goles: 5 },
    { jugador: "Cristian Benjumea", goles: 5 },
    { jugador: "Jeison Santa", goles: 5 },
    { jugador: "Víctor Castilla (Toto)", goles: 5 },
    { jugador: "Jhonnier DLC", goles: 4 },
    { jugador: "Frederick Molina", goles: 4 },
    { jugador: "Esteban Hinojosa", goles: 4 },
    { jugador: "Omar Peralta", goles: 4 },
    { jugador: "Brayan Salas", goles: 4 },
    { jugador: "Arnoldo Daza", goles: 3 },
    { jugador: "Frank Ramírez", goles: 3 },
    { jugador: "Emanuel Celedón", goles: 3 },
    { jugador: "Bryan Pallares", goles: 3 },
    { jugador: "Nadim Camall", goles: 3 },
    { jugador: "Carlos Romero", goles: 2 },
    { jugador: "Andrés Salazar", goles: 2 },
    { jugador: "Mariano Amaris", goles: 2 },
    { jugador: "Ronald Rojas", goles: 2 },
    { jugador: "Camilo Laborde", goles: 2 },
    { jugador: "Ian Need", goles: 2 },
    { jugador: "Jeysson Henríquez", goles: 2 },
    { jugador: "Jorge España", goles: 2 },
    { jugador: "Ronald Andrade", goles: 2 },
    { jugador: "Julián Charris", goles: 2 },
    { jugador: "Andrés Cuadrado", goles: 2 },
    { jugador: "Juan Mora", goles: 1 },
    { jugador: "Andrés Galindo", goles: 1 },
    { jugador: "Juan Vargas", goles: 1 },
    { jugador: "Daniel Periñan", goles: 1 },
    { jugador: "Jesús Pertuz", goles: 1 },
    { jugador: "Miguel Guerra", goles: 1 },
    { jugador: "Sergio Blanchar", goles: 1 },
    { jugador: "Óscar Pérez", goles: 1 },
    { jugador: "Eudes Pavajeau", goles: 1 },
    { jugador: "Meyssal Murillo", goles: 1 },
  ],
  goleadorLiga: { jugador: "José Hernández", goles: 29 },
  arqueros: [
    { arquero: "Brayan Cadena", golesRecibidos: 39 },
    { arquero: "Leonardo Cadena", golesRecibidos: 40 },
    { arquero: "Fernando Gómez", golesRecibidos: 41 },
    { arquero: "Santiago Sánchez", golesRecibidos: 42 },
    { arquero: "Brayan Ospino", golesRecibidos: 44 },
    { arquero: "Camilo Laborde", golesRecibidos: 45 },
    { arquero: "Carlos Barraza", golesRecibidos: 52 },
    { arquero: "Jorge Cotes", golesRecibidos: 59 },
    { arquero: "Pipe Castillejo", golesRecibidos: 69 },
  ],
  mejorArquero: { arquero: "Brayan Cadena", golesRecibidos: 39 },
  cuartos: ["Fiorentina 9 - Celta de Vigo 8", "Inglaterra 5 - Alemania 2"],
  semifinales: ["Sport Boys 10 - Inglaterra 4", "Holanda 12 - Fiorentina 7"],
  final: "Sport Boys 4 - Holanda 4",
  ganador: "Sport Boys",
};

// Arqueros por equipo para Liga PPT #14
export const ARQUEROS_LIGA_14: Record<string, string> = {
  Brasil: "Fernando Gómez",
  "Equipo Rocket": "Brayan Cadena",
  "River Plate": "Nicolás Baute",
  Fiorentina: "Pipe Castillejo",
  Wolverhampton: "Santiago Sánchez",
  "Eintracht Frankfurt": "Carlos Barraza",
  "E. Frankfurt": "Carlos Barraza",
  " Frankfurt": "Carlos Barraza",
  Junior: "Leonardo Cadena",
  "Palermo FC": "Brayan Ospino",
  "VfL Wolfsburgo": "Camilo Laborde",
};

export const ARQUEROS_POR_LIGA: Record<number, Record<string, string>> = {
  5: ARQUEROS_LIGA_5,
  6: ARQUEROS_LIGA_6,
  7: ARQUEROS_LIGA_7,
  8: ARQUEROS_LIGA_8,
  9: ARQUEROS_LIGA_9,
  10: ARQUEROS_LIGA_10,
  11: ARQUEROS_LIGA_11,
  12: ARQUEROS_LIGA_12,
  13: ARQUEROS_LIGA_13,
  14: ARQUEROS_LIGA_14,
};

// Datos para Liga PPT #14 (actualizados con resultados reales de Jornada 1)
export const LIGA_14 = {
  tablaGeneral: [
    {
      equipo: "Wolverhampton",
      pj: 35,
      victorias: 18,
      empates: 3,
      derrotas: 14,
      porcentajeVictorias: 51,
      puntos: 39,
    },
    {
      equipo: "Junior",
      pj: 33,
      victorias: 14,
      empates: 5,
      derrotas: 14,
      porcentajeVictorias: 42,
      puntos: 33,
    },
    {
      equipo: "Brasil",
      pj: 38,
      victorias: 17,
      empates: 7,
      derrotas: 14,
      porcentajeVictorias: 45,
      puntos: 41,
    },
    {
      equipo: "Palermo FC",
      pj: 34,
      victorias: 13,
      empates: 9,
      derrotas: 12,
      porcentajeVictorias: 38,
      puntos: 35,
    },
    {
      equipo: "River Plate",
      pj: 33,
      victorias: 11,
      empates: 8,
      derrotas: 14,
      porcentajeVictorias: 33,
      puntos: 30,
    },
    {
      equipo: "VfL Wolfsburgo",
      pj: 36,
      victorias: 17,
      empates: 5,
      derrotas: 14,
      porcentajeVictorias: 47,
      puntos: 39,
    },
    {
      equipo: "Fiorentina",
      pj: 30,
      victorias: 10,
      empates: 7,
      derrotas: 13,
      porcentajeVictorias: 33,
      puntos: 27,
    },
    {
      equipo: "Equipo Rocket",
      pj: 36,
      victorias: 15,
      empates: 5,
      derrotas: 16,
      porcentajeVictorias: 42,
      puntos: 35,
    },
    {
      equipo: "Eintracht Frankfurt",
      pj: 27,
      victorias: 7,
      empates: 9,
      derrotas: 11,
      porcentajeVictorias: 26,
      puntos: 23,
    },
  ],
  jornadas: [
    {
      nombre: "Jornada 1",
      resultados: [
        {
          equipo: "VfL Wolfsburgo",
          pj: 17,
          v: 10,
          e: 3,
          d: 4,
          puntos: 23,
          porcentajeVictorias: 59,
        },
        {
          equipo: "Equipo Rocket",
          pj: 19,
          v: 9,
          e: 3,
          d: 7,
          puntos: 21,
          porcentajeVictorias: 47,
        },
        {
          equipo: "Brasil",
          pj: 19,
          v: 8,
          e: 4,
          d: 7,
          puntos: 20,
          porcentajeVictorias: 42,
        },
        {
          equipo: "Palermo FC",
          pj: 15,
          v: 6,
          e: 4,
          d: 5,
          puntos: 16,
          porcentajeVictorias: 40,
        },
        {
          equipo: "E. Frankfurt",
          pj: 13,
          v: 5,
          e: 6,
          d: 2,
          puntos: 16,
          porcentajeVictorias: 38,
        },
        {
          equipo: "River Plate",
          pj: 16,
          v: 4,
          e: 5,
          d: 7,
          puntos: 13,
          porcentajeVictorias: 25,
        },
        {
          equipo: "Fiorentina",
          pj: 12,
          v: 4,
          e: 3,
          d: 5,
          puntos: 11,
          porcentajeVictorias: 33,
        },
        {
          equipo: "Wolverhampton",
          pj: 13,
          v: 4,
          e: 3,
          d: 6,
          puntos: 11,
          porcentajeVictorias: 31,
        },
        {
          equipo: "Junior",
          pj: 14,
          v: 2,
          e: 3,
          d: 9,
          puntos: 7,
          porcentajeVictorias: 14,
        },
      ],
    },
    {
      nombre: "Jornada 2",
      resultados: [
        {
          equipo: "Wolverhampton",
          pj: 22,
          v: 14,
          e: 0,
          d: 8,
          puntos: 28,
          porcentajeVictorias: 64,
        },
        {
          equipo: "Junior",
          pj: 19,
          v: 12,
          e: 2,
          d: 5,
          puntos: 26,
          porcentajeVictorias: 63,
        },
        {
          equipo: "Brasil",
          pj: 19,
          v: 9,
          e: 3,
          d: 7,
          puntos: 21,
          porcentajeVictorias: 47,
        },
        {
          equipo: "Palermo FC",
          pj: 19,
          v: 7,
          e: 5,
          d: 7,
          puntos: 19,
          porcentajeVictorias: 37,
        },
        {
          equipo: "River Plate",
          pj: 17,
          v: 7,
          e: 3,
          d: 7,
          puntos: 17,
          porcentajeVictorias: 41,
        },
        {
          equipo: "VfL Wolfsburgo",
          pj: 19,
          v: 7,
          e: 2,
          d: 10,
          puntos: 16,
          porcentajeVictorias: 37,
        },
        {
          equipo: "Fiorentina",
          pj: 18,
          v: 6,
          e: 4,
          d: 8,
          puntos: 16,
          porcentajeVictorias: 33,
        },
        {
          equipo: "Equipo Rocket",
          pj: 17,
          v: 6,
          e: 2,
          d: 9,
          puntos: 14,
          porcentajeVictorias: 35,
        },
        {
          equipo: "Eintracht Frankfurt",
          pj: 14,
          v: 2,
          e: 3,
          d: 9,
          puntos: 7,
          porcentajeVictorias: 14,
        },
      ],
    },
    {
      nombre: "Jornada 2",
      resultados: [
        {
          equipo: "Brasil",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "Equipo Rocket",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "River Plate",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "Fiorentina",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "Wolverhampton",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "E. Frankfurt",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "Junior",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "Palermo FC",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "VfL Wolfsburgo",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
      ],
    },
    {
      nombre: "Jornada 3",
      resultados: [
        {
          equipo: "Brasil",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "Equipo Rocket",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "River Plate",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "Fiorentina",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "Wolverhampton",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "E. Frankfurt",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "Junior",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "Palermo FC",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "VfL Wolfsburgo",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
      ],
    },
    {
      nombre: "Jornada 4",
      resultados: [
        {
          equipo: "Brasil",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "Equipo Rocket",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "River Plate",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "Fiorentina",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "Wolverhampton",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "E. Frankfurt",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "Junior",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "Palermo FC",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "VfL Wolfsburgo",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
      ],
    },
    {
      nombre: "Jornada 5",
      resultados: [
        {
          equipo: "Brasil",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "Equipo Rocket",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "River Plate",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "Fiorentina",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "Wolverhampton",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "Eintracht Frankfurt",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "Junior",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "Palermo FC",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "VfL Wolfsburgo",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
      ],
    },
    {
      nombre: "Jornada 6",
      resultados: [
        {
          equipo: "Brasil",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "Equipo Rocket",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "River Plate",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "Fiorentina",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "Wolverhampton",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "Eintracht Frankfurt",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "Junior",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "Palermo FC",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
        {
          equipo: "VfL Wolfsburgo",
          pj: 0,
          v: 0,
          e: 0,
          d: 0,
          puntos: 0,
          porcentajeVictorias: 0,
        },
      ],
    },
  ],
  goleadoresTotales: [
    { jugador: "José Hernández", goles: 9 },
    { jugador: "Jürgen Hassler", goles: 6 },
    { jugador: "Andrés Farfán", goles: 6 },
    { jugador: "Víctor Castilla (Toto)", goles: 5 },
    { jugador: "Juan Dybala", goles: 5 },
    { jugador: "Sergio Barrera", goles: 5 },
    { jugador: "Keiler Fonseca", goles: 5 },
    { jugador: "Andrés Salazar", goles: 4 },
    { jugador: "Dairo Martínez", goles: 4 },
    { jugador: "Carlos Armenta", goles: 4 },
    { jugador: "Santiago Corzo", goles: 4 },
    { jugador: "Jefferson Almanza", goles: 4 },
    { jugador: "Kevin Pineda", goles: 4 },
    { jugador: "Emanuel Navarro (Goat)", goles: 4 },
    { jugador: "Ronald Rojas", goles: 4 },
    { jugador: "Jeison Santa", goles: 4 },
    { jugador: "Keni Contreras", goles: 4 },
    { jugador: "Mariano Amaris", goles: 3 },
    { jugador: "Juan DLC", goles: 3 },
    { jugador: "Andy Córdoba (Pingui)", goles: 3 },
    { jugador: "Juan Tellez", goles: 2 },
    { jugador: "Cristian Benjumea", goles: 2 },
    { jugador: "José Mosquera", goles: 2 },
    { jugador: "Narent Rojas", goles: 2 },
    { jugador: "Arnold Castillo", goles: 2 },
    { jugador: "Bryan Pallares", goles: 2 },
    { jugador: "Cristian Trujillo", goles: 2 },
    { jugador: "Carlos Romero", goles: 2 },
    { jugador: "Ronald Andrade", goles: 1 },
    { jugador: "José Henao 2", goles: 1 },
    { jugador: "Miguel Guerra", goles: 1 },
    { jugador: "Óscar DLC", goles: 1 },
    { jugador: "Ian Need", goles: 1 },
    { jugador: "Alexander Benitez", goles: 1 },
    { jugador: "Nadim Camall", goles: 1 },
    { jugador: "Jairo Galván", goles: 1 },
    { jugador: "Esteban Hinojosa", goles: 1 },
    { jugador: "Jeysson Henríquez", goles: 1 },
    { jugador: "Emanuel Celedón", goles: 1 },
    { jugador: "Daniel Cuadros", goles: 1 },
    { jugador: "Fabricio Rizo", goles: 1 },
    { jugador: "Sergio Blanchar", goles: 1 },
    { jugador: "Juanse Pinedo", goles: 1 },
  ],
  goleadorLiga: { jugador: "José Hernández", goles: 9 },
  arqueros: [
    { arquero: "Carlos Barraza", golesRecibidos: 11 },
    { arquero: "Brayan Ospino", golesRecibidos: 12 },
    { arquero: "Pipe Castillejo", golesRecibidos: 13 },
    { arquero: "Leonardo Cadena", golesRecibidos: 14 },
    { arquero: "Nicolás Baute", golesRecibidos: 14 },
    { arquero: "Fernando Gómez", golesRecibidos: 14 },
    { arquero: "Santiago Sánchez", golesRecibidos: 14 },
    { arquero: "Camilo Laborde", golesRecibidos: 14 },
    { arquero: "Brayan Cadena", golesRecibidos: 16 },
  ],
  mejorArquero: { arquero: "Carlos Barraza", golesRecibidos: 11 },
  cuartos: [],
  semifinales: [],
  final: "",
  ganador: "",
};
