/** Fila del ranking de más ganadores. `champions` y `mundial` son títulos aparte de las ligas regulares (0 si no aplica). */
export type MasGanador = {
  nombre: string;
  titulos: number;
  ligas: number[];
  champions?: number;
  mundial?: number;
};

export const MAS_GANADORES: MasGanador[] = [
  { nombre: "Emanuel Navarro (Goat)", titulos: 7, ligas: [2, 3, 4, 5, 6, 7, 17] },
  { nombre: "Cristian Benjumea", titulos: 5, ligas: [1, 3, 7, 8, 12] },
  { nombre: "Frank Ramírez", titulos: 5, ligas: [5, 7, 11, 13, 15] },
  { nombre: "Keni Contreras", titulos: 5, ligas: [5, 7, 8, 11, 17] },
  { nombre: "Eudes Pavajeau", titulos: 4, ligas: [4, 8, 10, 17] },
  { nombre: "Mariano Amaris", titulos: 4, ligas: [1, 3, 4, 11] },
  { nombre: "Pipe Castillejo", titulos: 4, ligas: [3, 4, 5, 8] },
  { nombre: "Andrés Farfán", titulos: 3, ligas: [1, 3, 4] },
  { nombre: "Andy Córdoba (Pingui)", titulos: 3, ligas: [8, 9, 10] },
  { nombre: "Brayan Cadena", titulos: 3, ligas: [9, 10, 13] },
  { nombre: "Camilo Laborde", titulos: 3, ligas: [3, 6, 7] },
  { nombre: "Daniel Cuadros", titulos: 3, ligas: [2, 4, 5] },
  { nombre: "Frederick Molina", titulos: 3, ligas: [7, 9, 12] },
  { nombre: "Jairo Galván", titulos: 3, ligas: [4, 10, 12] },
  { nombre: "Jefferson Almanza", titulos: 3, ligas: [6, 11, 12] },
  { nombre: "Juan Mora", titulos: 3, ligas: [3, 6, 8] },
  { nombre: "Lucas Benjumea", titulos: 3, ligas: [2, 5, 8] },
  { nombre: "Ronald Rojas", titulos: 3, ligas: [10, 11, 15] },
  { nombre: "Yassir Fuentes", titulos: 3, ligas: [14, 16, 17] },
  { nombre: "Cristian Trujillo", titulos: 2, ligas: [12, 14] },
  { nombre: "Emanuel Celedón", titulos: 2, ligas: [1, 5] },
  { nombre: "Esteban Galván", titulos: 2, ligas: [4, 15] },
  { nombre: "Henry Hernández", titulos: 2, ligas: [2, 9] },
  { nombre: "Hernán Medrano", titulos: 2, ligas: [9, 13] },
  { nombre: "Jesús Pertuz", titulos: 2, ligas: [13, 14] },
  { nombre: "Jhonnier DLC", titulos: 2, ligas: [2, 5] },
  { nombre: "José Hernández", titulos: 2, ligas: [9, 13] },
  { nombre: "José Laborde", titulos: 2, ligas: [6, 7] },
  { nombre: "Juan DLC", titulos: 2, ligas: [6, 15] },
  { nombre: "Julio Ochoa", titulos: 2, ligas: [9, 13] },
  { nombre: "Jürgen Hassler", titulos: 2, ligas: [8, 11] },
  { nombre: "Kevin Pineda", titulos: 2, ligas: [14, 17] },
  { nombre: "Sebastian Pérez", titulos: 2, ligas: [1, 2] },
  { nombre: "Andrés Ramírez", titulos: 1, ligas: [15] },
  { nombre: "Andrés Salazar", titulos: 1, ligas: [14] },
  { nombre: "Arnold Castillo", titulos: 1, ligas: [13] },
  { nombre: "Brayan Ospino", titulos: 1, ligas: [11] },
  { nombre: "Carlos Romero", titulos: 1, ligas: [12] },
  { nombre: "Carlos Vega", titulos: 1, ligas: [16] },
  { nombre: "Daniel Prens", titulos: 1, ligas: [1] },
  { nombre: "Diego Felipe", titulos: 1, ligas: [2] },
  { nombre: "Eduardo Sarmiento (Mou)", titulos: 1, ligas: [15] },
  { nombre: "Edward Brito (Titi)", titulos: 1, ligas: [6] },
  { nombre: "Edwin Martínez", titulos: 1, ligas: [17] },
  { nombre: "Elías Lacera", titulos: 1, ligas: [6] },
  { nombre: "Esteban Hinojosa", titulos: 1, ligas: [16] },
  { nombre: "Fernando Gómez", titulos: 1, ligas: [14] },
  { nombre: "Héctor Duque", titulos: 1, ligas: [17] },
  { nombre: "Hernán García", titulos: 1, ligas: [16] },
  { nombre: "Jaime Machado", titulos: 1, ligas: [16] },
  { nombre: "Jeison Santa", titulos: 1, ligas: [16] },
  { nombre: "Jesús Abuchaibe", titulos: 1, ligas: [3] },
  { nombre: "Jesús Cartagena", titulos: 1, ligas: [10] },
  { nombre: "Jesús Solano", titulos: 1, ligas: [14] },
  { nombre: "Jeysson Henríquez", titulos: 1, ligas: [11] },
  { nombre: "José Mosquera", titulos: 1, ligas: [14] },
  { nombre: "José Viña", titulos: 1, ligas: [7] },
  { nombre: "Juan Dybala", titulos: 1, ligas: [9] },
  { nombre: "Keyner Vides", titulos: 1, ligas: [17] },
  { nombre: "Mario Orozco", titulos: 1, ligas: [12] },
  { nombre: "Omar Peralta", titulos: 1, ligas: [10] },
  { nombre: "Óscar DLC", titulos: 1, ligas: [15] },
  { nombre: "Óscar Pérez", titulos: 1, ligas: [16] },
  { nombre: "Pier Rizo", titulos: 1, ligas: [5] },
  { nombre: "Ronaldo", titulos: 1, ligas: [3] },
  { nombre: "Santiago Corzo", titulos: 1, ligas: [16] },
  { nombre: "Santiago Sánchez", titulos: 1, ligas: [12] },
];
