export const MAS_GANADORES = [
  { nombre: "Emanuel Navarro (Goat)", titulos: 6, ligas: [2, 3, 4, 5, 6, 7] },
  { nombre: "Cristian Benjumea", titulos: 5, ligas: [1, 2, 7, 8, 12] },
  { nombre: "Frank Ramírez", titulos: 4, ligas: [5, 7, 11, 13] },
  { nombre: "Mariano Amaris", titulos: 4, ligas: [1, 3, 4, 11] },
  { nombre: "Keni Contreras", titulos: 4, ligas: [5, 7, 8, 11] },
  { nombre: "Pipe Castillejo", titulos: 4, ligas: [3, 4, 5, 8] },
  { nombre: "Brayan Cadena", titulos: 3, ligas: [9, 10, 13] },
  { nombre: "Juan Mora", titulos: 3, ligas: [3, 6, 8] },
  { nombre: "Andy Córdoba (Pingui)", titulos: 3, ligas: [8, 9, 10] },
  { nombre: "Camilo Laborde", titulos: 3, ligas: [3, 6, 7] },
  { nombre: "Daniel Cuadros", titulos: 3, ligas: [2, 4, 5] },
  { nombre: "Eudes Pavajeau", titulos: 3, ligas: [4, 8, 10] },
  { nombre: "Frederick Molina", titulos: 3, ligas: [7, 9, 12] },
  { nombre: "Jairo Galván", titulos: 3, ligas: [4, 10, 12] },
  { nombre: "Jefferson Almanza", titulos: 3, ligas: [6, 11, 12] },
  { nombre: "Lucas Benjumea", titulos: 3, ligas: [2, 5, 8] },
  { nombre: "Andrés Farfán", titulos: 3, ligas: [1, 3, 4] },
  { nombre: "Hernán Medrano", titulos: 2, ligas: [9, 13] },
  { nombre: "José Hernández", titulos: 2, ligas: [9, 13] },
  { nombre: "Emanuel Celedón", titulos: 2, ligas: [1, 5] },
  { nombre: "Jhonnier DLC", titulos: 2, ligas: [2, 5] },
  { nombre: "José Laborde", titulos: 2, ligas: [6, 7] },
  { nombre: "Jürgen Hassler", titulos: 2, ligas: [8, 11] },
  { nombre: "Ronald Rojas", titulos: 2, ligas: [10, 11] },
  { nombre: "Sebastian Pérez", titulos: 2, ligas: [1, 2] },
  { nombre: "Henry Hernández", titulos: 2, ligas: [2, 9] },
  { nombre: "Jesús Pertúz", titulos: 1, ligas: [13] },
  { nombre: "Arnold Castillo", titulos: 1, ligas: [13] },
  { nombre: "Mario Orozco", titulos: 1, ligas: [12] },
  { nombre: "Brayan Ospino", titulos: 1, ligas: [11] },
  { nombre: "Carlos Romero", titulos: 1, ligas: [12] },
  { nombre: "Cristian Trujillo", titulos: 1, ligas: [12] },
  { nombre: "Diego Felipe", titulos: 1, ligas: [2] },
  { nombre: "Edward Brito (Titi)", titulos: 1, ligas: [6] },
  { nombre: "Elías Lacera", titulos: 1, ligas: [6] },
  { nombre: "Esteban Galván", titulos: 1, ligas: [4] },
  { nombre: "Jesús Abuchaibe", titulos: 1, ligas: [3] },
  { nombre: "Jesús Cartagena", titulos: 1, ligas: [10] },
  { nombre: "Jeysson Henríquez", titulos: 1, ligas: [11] },
  { nombre: "José Viña", titulos: 1, ligas: [7] },
  { nombre: "Juan DLC", titulos: 1, ligas: [6] },
  { nombre: "Juan Dybala", titulos: 1, ligas: [9] },
  { nombre: "Julio David", titulos: 1, ligas: [9] },
  { nombre: "Omar Peralta", titulos: 1, ligas: [10] },
  { nombre: "Pier Rizo", titulos: 1, ligas: [5] },
  { nombre: "Ronaldo", titulos: 1, ligas: [3] },
  { nombre: "Santiago Sánchez", titulos: 1, ligas: [12] },
  { nombre: "Sergio Blanchar", titulos: 1, ligas: [11] },
  { nombre: "Daniel Prens", titulos: 1, ligas: [1] },
];
