export const GOLEADORES_HISTORICOS = [
  { nombre: "Jürgen Hassler", goles: 153 },
  { nombre: "Andrés Farfán", goles: 148 },
  { nombre: "José Hernández", goles: 135 },
  { nombre: "Keni Contreras", goles: 131 },
  { nombre: "Emanuel Navarro (Goat)", goles: 129 },
  { nombre: "Juan de la Cruz", goles: 116 },
  { nombre: "Jairo Galván", goles: 87 },
  { nombre: "Fabricio Rizo", goles: 86 },
  { nombre: "Jefferson Almanza", goles: 69 },
  { nombre: "Jeison Santa", goles: 62 },
  { nombre: "Mariano Amaris", goles: 59 },
  { nombre: "Lucas Benjumea", goles: 56 },
  { nombre: "Henry Hernández", goles: 54 },
  { nombre: "Frederick Molina", goles: 54 },
  { nombre: "Cristian Benjumea", goles: 54 },
  { nombre: "Esteban Galván", goles: 41 },
  { nombre: "Andy Córdoba (Pingui)", goles: 40 },
  { nombre: "Mario Orozco", goles: 40 },
  { nombre: "Emanuel Celedón", goles: 39 },
  { nombre: "Eudes Pavajeau", goles: 38 },
  { nombre: "Ronald Rojas", goles: 35 },
  { nombre: "Santiago Corzo", goles: 35 },
  { nombre: "Yassir Fuentes", goles: 34 },
  { nombre: "Camilo Laborde", goles: 33 },
  { nombre: "Sergio Blanchar", goles: 32 },
  { nombre: "Julio Ochoa", goles: 31 },
  { nombre: "José Viña", goles: 30 },
  { nombre: "Carlos Armenta", goles: 29 },
  { nombre: "Nico Yamal", goles: 29 },
  { nombre: "Frank Ramírez", goles: 28 },
  { nombre: "Víctor Castilla (Toto)", goles: 26 },
  { nombre: "Juan Dybala", goles: 25 },
  { nombre: "Hernán Medrano", goles: 24 },
  { nombre: "Cristian Trujillo", goles: 23 },
  { nombre: "Kevin Pineda", goles: 22 },
  { nombre: "Elías Lacera", goles: 19 },
  { nombre: "Carlos Romero", goles: 19 },
  { nombre: "Edward Brito (Titi)", goles: 18 },
  { nombre: "Luis Mariano", goles: 17 },
  { nombre: "Pier Rizo", goles: 17 },
  { nombre: "Jhonnier DLC", goles: 17 },
  { nombre: "Omar Peralta", goles: 17 },
  { nombre: "Pipe New", goles: 16 },
  { nombre: "Juan Mora", goles: 16 },
  { nombre: "Jesús Pertuz", goles: 15 },
  { nombre: "Julián Charris", goles: 14 },
  { nombre: "Daniel Cuadros", goles: 14 },
  { nombre: "Keiler Fonseca", goles: 14 },
  { nombre: "Sergio Barrera", goles: 14 },
  { nombre: "José Mosquera", goles: 11 },
  { nombre: "Camilo Torres", goles: 10 },
  { nombre: "Dairo Martínez", goles: 9 },
  { nombre: "Narent Rojas", goles: 8 },
  { nombre: "Arnold Castillo", goles: 8 },
  { nombre: "Jorge Farfán", goles: 7 },
  { nombre: "Luis Rico", goles: 7 },
  { nombre: "Jefferson Medrano", goles: 6 },
  { nombre: "Juan Sebastian", goles: 4 },
  { nombre: "Esteban Hinojosa", goles: 4 },
  { nombre: "Brayan Salas", goles: 4 },
  { nombre: "Jaime", goles: 3 },
  { nombre: "Junior", goles: 3 },
  { nombre: "Trespa", goles: 3 },
  { nombre: "Nadim Camall", goles: 3 },
  { nombre: "Arnoldo Daza", goles: 3 },
  { nombre: "Bryan Pallares", goles: 3 },
  { nombre: "Breiner Corzo (Mene)", goles: 2 },
  { nombre: "Santiago Sánchez", goles: 2 },
  { nombre: "Sebastian Pérez", goles: 2 },
  { nombre: "Óscar Pérez", goles: 2 },
  { nombre: "Andrés Cuadrado", goles: 2 },
  { nombre: "Ian Need", goles: 2 },
  { nombre: "Andrés Salazar", goles: 2 },
  { nombre: "Jeysson Henríquez", goles: 2 },
  { nombre: "Ronald Andrade", goles: 2 },
  { nombre: "Jorge España", goles: 2 },
  { nombre: "Daniel Prens", goles: 1 },
  { nombre: "José Celedón", goles: 1 },
  { nombre: "Lucho Alejandro", goles: 1 },
  { nombre: "Moncho", goles: 1 },
  { nombre: "Samuel", goles: 1 },
  { nombre: "Meyssal Murillo", goles: 1 },
  { nombre: "Miguel Guerra", goles: 1 },
  { nombre: "Juan Vargas", goles: 1 },
  { nombre: "Andrés Galindo", goles: 1 },
  { nombre: "Daniel Periñan", goles: 1 },
];
