export const GOLEADORES_HISTORICOS = [
  { nombre: "José Hernández", goles: 240 },
  { nombre: "Jürgen Hassler", goles: 206 },
  { nombre: "Andrés Farfán", goles: 200 },
  { nombre: "Keni Contreras", goles: 165 },
  { nombre: "Juan DLC", goles: 161 },
  { nombre: "Emanuel Navarro (Goat)", goles: 153 },
  { nombre: "Jeison Santa", goles: 112 },
  { nombre: "Jairo Galván", goles: 106 },
  { nombre: "Santiago Corzo", goles: 106 },
  { nombre: "Fabricio Rizo", goles: 102 },
  { nombre: "Yassir Fuentes", goles: 94 },
  { nombre: "Jefferson Almanza", goles: 77 },
  { nombre: "Víctor Castilla (Toto)", goles: 74 },
  { nombre: "Ronald Rojas", goles: 71 },
  { nombre: "Henry Hernández", goles: 68 },
  { nombre: "Mariano Amaris", goles: 68 },
  { nombre: "Cristian Benjumea", goles: 67 },
  { nombre: "Keiler Fonseca", goles: 65 },
  { nombre: "Andy Córdoba (Pingui)", goles: 64 },
  { nombre: "Frederick Molina", goles: 64 },
  { nombre: "Juanda Dybala", goles: 63 },
  { nombre: "Hernán Medrano", goles: 60 },
  { nombre: "Kevin Pineda", goles: 60 },
  { nombre: "Lucas Benjumea", goles: 56 },
  { nombre: "Eduardo Sarmiento (Mou)", goles: 55 },
  { nombre: "Víctor López", goles: 55 },
  { nombre: "Arnold Castillo", goles: 54 },
  { nombre: "Emanuel Celedón", goles: 50 },
  { nombre: "Esteban Galván", goles: 49 },
  { nombre: "Eudes Pavajeau", goles: 49 },
  { nombre: "Carlos Armenta", goles: 46 },
  { nombre: "José Mosquera", goles: 46 },
  { nombre: "Nico Yamal", goles: 46 },
  { nombre: "Carlos Romero", goles: 45 },
  { nombre: "Jossimar Cujia (Pollo)", goles: 45 },
  { nombre: "Camilo Laborde", goles: 43 },
  { nombre: "Mario Orozco", goles: 40 },
  { nombre: "José Viña", goles: 38 },
  { nombre: "Dairo Martínez", goles: 36 },
  { nombre: "José Franco", goles: 35 },
  { nombre: "Frank Ramírez", goles: 33 },
  { nombre: "Sergio Barrera", goles: 32 },
  { nombre: "Julio Ochoa", goles: 31 },
  { nombre: "Steven Cubides", goles: 31 },
  { nombre: "Cristian Trujillo", goles: 29 },
  { nombre: "Elías Lacera", goles: 28 },
  { nombre: "Edwin Martínez", goles: 27 },
  { nombre: "Narent Rojas", goles: 27 },
  { nombre: "Andrés Salazar", goles: 25 },
  { nombre: "Daniel Cuadros", goles: 25 },
  { nombre: "Jesús Pertuz", goles: 25 },
  { nombre: "Omar Peralta", goles: 22 },
  { nombre: "Edward Brito (Titi)", goles: 21 },
  { nombre: "Ruber Martínez", goles: 21 },
  { nombre: "Jesús Bullones", goles: 20 },
  { nombre: "Roberto Arrieta (Cante)", goles: 20 },
  { nombre: "Jesús Trespalacios", goles: 19 },
  { nombre: "Juan Mora", goles: 19 },
  { nombre: "Jhonnier DLC", goles: 18 },
  { nombre: "Juanse López", goles: 18 },
  { nombre: "Esteban Hinojosa (Wara)", goles: 17 },
  { nombre: "Luis Mariano", goles: 17 },
  { nombre: "Pier Rizo", goles: 17 },
  { nombre: "Jesús Vergara (Chula)", goles: 16 },
  { nombre: "Julián Charris", goles: 16 },
  { nombre: "Pipe New", goles: 16 },
  { nombre: "Jaime Machado", goles: 15 },
  { nombre: "Kevin Gómez", goles: 15 },
  { nombre: "Sebastian Castaño", goles: 14 },
  { nombre: "Nadim Camall", goles: 13 },
  { nombre: "Óscar Mendoza", goles: 13 },
  { nombre: "Anderson Gómez", goles: 12 },
  { nombre: "Alexis Marín", goles: 11 },
  { nombre: "Camilo Torres", goles: 11 },
  { nombre: "Héctor Duque", goles: 10 },
  { nombre: "Jaime Medrano", goles: 10 },
  { nombre: "Eduardo Carrillo (Musiala)", goles: 9 },
  { nombre: "Jesús Solano", goles: 8 },
  { nombre: "José Henao 2", goles: 8 },
  { nombre: "Juanse Pinedo", goles: 8 },
  { nombre: "Bryan Pallares", goles: 7 },
  { nombre: "Jorge Farfán", goles: 7 },
  { nombre: "Luis Rico", goles: 7 },
  { nombre: "Andrés Valle", goles: 6 },
  { nombre: "Breiner Corzo (Mene)", goles: 6 },
  { nombre: "Jefferson Medrano", goles: 6 },
  { nombre: "Jhan C. Martínez", goles: 6 },
  { nombre: "Juan Tellez", goles: 6 },
  { nombre: "Luis Serge", goles: 6 },
  { nombre: "Miguel Guerra", goles: 5 },
  { nombre: "Brayan Salas", goles: 4 },
  { nombre: "Juan Sebastian", goles: 4 },
  { nombre: "Juan Vargas", goles: 4 },
  { nombre: "Juanse Tibaduiza", goles: 4 },
  { nombre: "Alexander Benitez", goles: 3 },
  { nombre: "Andrés Cuadrado", goles: 3 },
  { nombre: "Arnoldo Daza", goles: 3 },
  { nombre: "Camilo Yepes", goles: 3 },
  { nombre: "Carlos López", goles: 3 },
  { nombre: "Daniel Trillos", goles: 3 },
  { nombre: "David Carballo", goles: 3 },
  { nombre: "Filgar Morales", goles: 3 },
  { nombre: "Ian Need", goles: 3 },
  { nombre: "Jereimy Niebles", goles: 3 },
  { nombre: "Jeysson Henríquez", goles: 3 },
  { nombre: "Juan Sánchez", goles: 3 },
  { nombre: "Junior", goles: 3 },
  { nombre: "Luis Suárez", goles: 3 },
  { nombre: "Óscar DLC", goles: 3 },
  { nombre: "Ronald Andrade", goles: 3 },
  { nombre: "Alejandro Macherna", goles: 2 },
  { nombre: "Antonio Calle", goles: 2 },
  { nombre: "Carlos Vega", goles: 2 },
  { nombre: "Fernando Gómez", goles: 2 },
  { nombre: "Jainer Álvarez", goles: 2 },
  { nombre: "Jorge España", goles: 2 },
  { nombre: "Orlando Díaz", goles: 2 },
  { nombre: "Óscar Pérez", goles: 2 },
  { nombre: "Santiago Sánchez", goles: 2 },
  { nombre: "Sebastian Pérez", goles: 2 },
  { nombre: "Youseth Nacith", goles: 2 },
  { nombre: "Andrés Galindo", goles: 1 },
  { nombre: "Brayan Ospino", goles: 1 },
  { nombre: "Daniel Periñan", goles: 1 },
  { nombre: "Daniel Prens", goles: 1 },
  { nombre: "Darío Daza", goles: 1 },
  { nombre: "Héctor Díaz", goles: 1 },
  { nombre: "Javier Cajamarca", goles: 1 },
  { nombre: "José Carrascal", goles: 1 },
  { nombre: "José Celedón", goles: 1 },
  { nombre: "Libardo del 5", goles: 1 },
  { nombre: "Lucho Alejandro", goles: 1 },
  { nombre: "Meyssal Murillo", goles: 1 },
  { nombre: "Mario Contreras", goles: 1 },
  { nombre: "Monchi", goles: 1 },
  { nombre: "Ronaldo Iglesia", goles: 1 },
  { nombre: "Samuel", goles: 1 },
];
