export const GOLEADORES_HISTORICOS = [
  { nombre: "Andrés Farfán", goles: 140 },
  { nombre: "Jürgen Hassler", goles: 132 },
  { nombre: "Emanuel Navarro (Goat)", goles: 118 },
  { nombre: "Keni Contreras", goles: 117 },
  { nombre: "José Hernández", goles: 106 },
  { nombre: "Juan DLC", goles: 99 },
  { nombre: "Fabricio Rizo", goles: 80 },
  { nombre: "Jairo Galván", goles: 78 },
  { nombre: "Jeison Santa", goles: 57 },
  { nombre: "Mariano Amaris", goles: 57 },
  { nombre: "Lucas Benjumea", goles: 56 },
  { nombre: "Jefferson Almanza", goles: 55 },
  { nombre: "Henry Hernández", goles: 54 },
  { nombre: "Frederick Molina", goles: 50 },
  { nombre: "Cristian Benjumea", goles: 49 },
  { nombre: "Eudes Pavajeau", goles: 37 },
  { nombre: "Emanuel Celedón", goles: 36 },
  { nombre: "Esteban Galván", goles: 35 },
  { nombre: "Ronald Rojas", goles: 33 },
  { nombre: "Camilo Laborde", goles: 31 },
  { nombre: "Sergio Blanchar", goles: 31 },
  { nombre: "Andy Córdoba (Pingui)", goles: 27 },
  { nombre: "Frank Ramírez", goles: 25 },
  { nombre: "Santiago Corzo", goles: 24 },
  { nombre: "José Viña", goles: 22 },
  { nombre: "Mario Orozco", goles: 22 },
  { nombre: "Carlos Armenta", goles: 21 },
  { nombre: "Víctor Castilla (Toto)", goles: 21 },
  { nombre: "Juan Dybala", goles: 20 },
  { nombre: "Nico Yamal", goles: 20 },
  { nombre: "Elías Lacera", goles: 19 },
  { nombre: "Hernán Medrano", goles: 18 },
  { nombre: "Yassir Fuentes", goles: 18 },
  { nombre: "Carlos Romero", goles: 17 },
  { nombre: "Julio David", goles: 17 },
  { nombre: "Kevin Pineda", goles: 17 },
  { nombre: "Luis Mariano", goles: 17 },
  { nombre: "Pier Rizo", goles: 17 },
  { nombre: "Cristian Trujillo", goles: 16 },
  { nombre: "Pipe New", goles: 16 },
  { nombre: "Juan Mora", goles: 15 },
  { nombre: "Jesús Pertuz", goles: 14 },
  { nombre: "Jhonnier DLC", goles: 13 },
  { nombre: "Omar Peralta", goles: 13 },
  { nombre: "Edward Brito (Titi)", goles: 12 },
  { nombre: "Julián Charris", goles: 12 },
  { nombre: "Daniel Cuadros", goles: 8 },
  { nombre: "Narent Rojas", goles: 8 },
  { nombre: "Jorge Farfán", goles: 7 },
  { nombre: "Juan Sebastian", goles: 4 },
  { nombre: "Jaime", goles: 3 },
  { nombre: "Junior", goles: 3 },
  { nombre: "Trespa", goles: 3 },
  { nombre: "Breiner Corzo (Mene)", goles: 2 },
  { nombre: "Santiago Sánchez", goles: 2 },
  { nombre: "Sebastian Pérez", goles: 2 },
  { nombre: "Daniel Prens", goles: 1 },
  { nombre: "José Celedón", goles: 1 },
  { nombre: "Lucho Alejandro", goles: 1 },
  { nombre: "Moncho", goles: 1 },
  { nombre: "Óscar Pérez", goles: 1 },
  { nombre: "Samuel", goles: 1 },
];
