/** Liga PPT #18 — datos a fecha 6 (tabla general, jornadas, goleadores, arqueros). */

const J18 = [
  {
    nombre: "Jornada 1",
    resultados: [
      {
        equipo: "Tottenham Hotspur",
        pj: 18,
        v: 11,
        e: 1,
        d: 6,
        puntos: 23,
        porcentajeVictorias: 61,
      },
      {
        equipo: "Galatasaray SK",
        pj: 16,
        v: 7,
        e: 5,
        d: 4,
        puntos: 19,
        porcentajeVictorias: 44,
      },
      {
        equipo: "Borussia Dortmund",
        pj: 16,
        v: 8,
        e: 2,
        d: 6,
        puntos: 18,
        porcentajeVictorias: 50,
      },
      {
        equipo: "Sporting Lisboa",
        pj: 14,
        v: 6,
        e: 4,
        d: 4,
        puntos: 16,
        porcentajeVictorias: 43,
      },
      {
        equipo: "Fiorentina",
        pj: 14,
        v: 6,
        e: 4,
        d: 4,
        puntos: 16,
        porcentajeVictorias: 43,
      },
      {
        equipo: "Arsenal F.C.",
        pj: 17,
        v: 7,
        e: 2,
        d: 8,
        puntos: 16,
        porcentajeVictorias: 41,
      },
      {
        equipo: "París Saint-Germain",
        pj: 17,
        v: 5,
        e: 3,
        d: 9,
        puntos: 13,
        porcentajeVictorias: 29,
      },
      {
        equipo: "Palermo F.C.",
        pj: 14,
        v: 3,
        e: 3,
        d: 8,
        puntos: 9,
        porcentajeVictorias: 21,
      },
      {
        equipo: "Inter de Milán",
        pj: 12,
        v: 3,
        e: 2,
        d: 7,
        puntos: 8,
        porcentajeVictorias: 25,
      },
    ],
  },
  {
    nombre: "Jornada 2",
    resultados: [
      {
        equipo: "Arsenal F.C.",
        pj: 23,
        v: 15,
        e: 4,
        d: 4,
        puntos: 34,
        porcentajeVictorias: 65,
      },
      {
        equipo: "Palermo F.C.",
        pj: 19,
        v: 9,
        e: 2,
        d: 8,
        puntos: 20,
        porcentajeVictorias: 47,
      },
      {
        equipo: "Sporting Lisboa",
        pj: 18,
        v: 8,
        e: 4,
        d: 6,
        puntos: 20,
        porcentajeVictorias: 44,
      },
      {
        equipo: "París Saint-Germain",
        pj: 12,
        v: 7,
        e: 2,
        d: 3,
        puntos: 16,
        porcentajeVictorias: 58,
      },
      {
        equipo: "Borussia Dortmund",
        pj: 17,
        v: 6,
        e: 4,
        d: 7,
        puntos: 16,
        porcentajeVictorias: 35,
      },
      {
        equipo: "Tottenham Hotspur",
        pj: 17,
        v: 6,
        e: 2,
        d: 9,
        puntos: 14,
        porcentajeVictorias: 35,
      },
      {
        equipo: "Galatasaray SK",
        pj: 11,
        v: 4,
        e: 3,
        d: 4,
        puntos: 11,
        porcentajeVictorias: 36,
      },
      {
        equipo: "Inter de Milán",
        pj: 14,
        v: 3,
        e: 1,
        d: 10,
        puntos: 7,
        porcentajeVictorias: 21,
      },
      {
        equipo: "Fiorentina",
        pj: 9,
        v: 1,
        e: 3,
        d: 5,
        puntos: 5,
        porcentajeVictorias: 11,
      },
    ],
  },
  {
    nombre: "Jornada 3",
    resultados: [
      {
        equipo: "Inter de Milán",
        pj: 17,
        v: 9,
        e: 3,
        d: 5,
        puntos: 21,
        porcentajeVictorias: 53,
      },
      {
        equipo: "Arsenal F.C.",
        pj: 15,
        v: 8,
        e: 4,
        d: 3,
        puntos: 20,
        porcentajeVictorias: 53,
      },
      {
        equipo: "Tottenham Hotspur",
        pj: 18,
        v: 8,
        e: 4,
        d: 6,
        puntos: 20,
        porcentajeVictorias: 44,
      },
      {
        equipo: "París Saint-Germain",
        pj: 14,
        v: 7,
        e: 4,
        d: 3,
        puntos: 18,
        porcentajeVictorias: 50,
      },
      {
        equipo: "Fiorentina",
        pj: 15,
        v: 6,
        e: 4,
        d: 5,
        puntos: 16,
        porcentajeVictorias: 40,
      },
      {
        equipo: "Borussia Dortmund",
        pj: 12,
        v: 5,
        e: 1,
        d: 6,
        puntos: 11,
        porcentajeVictorias: 42,
      },
      {
        equipo: "Galatasaray SK",
        pj: 16,
        v: 4,
        e: 3,
        d: 9,
        puntos: 11,
        porcentajeVictorias: 25,
      },
      {
        equipo: "Sporting Lisboa",
        pj: 11,
        v: 2,
        e: 5,
        d: 4,
        puntos: 9,
        porcentajeVictorias: 18,
      },
      {
        equipo: "Palermo F.C.",
        pj: 12,
        v: 2,
        e: 2,
        d: 8,
        puntos: 6,
        porcentajeVictorias: 17,
      },
    ],
  },
  {
    nombre: "Jornada 4",
    resultados: [
      {
        equipo: "Borussia Dortmund",
        pj: 21,
        v: 14,
        e: 4,
        d: 3,
        puntos: 32,
        porcentajeVictorias: 67,
      },
      {
        equipo: "Sporting Lisboa",
        pj: 16,
        v: 7,
        e: 3,
        d: 6,
        puntos: 17,
        porcentajeVictorias: 44,
      },
      {
        equipo: "Fiorentina",
        pj: 14,
        v: 6,
        e: 3,
        d: 5,
        puntos: 15,
        porcentajeVictorias: 43,
      },
      {
        equipo: "Tottenham Hotspur",
        pj: 14,
        v: 5,
        e: 5,
        d: 4,
        puntos: 15,
        porcentajeVictorias: 36,
      },
      {
        equipo: "Arsenal F.C.",
        pj: 13,
        v: 4,
        e: 6,
        d: 3,
        puntos: 14,
        porcentajeVictorias: 31,
      },
      {
        equipo: "París Saint-Germain",
        pj: 14,
        v: 4,
        e: 4,
        d: 6,
        puntos: 12,
        porcentajeVictorias: 29,
      },
      {
        equipo: "Galatasaray SK",
        pj: 15,
        v: 4,
        e: 2,
        d: 9,
        puntos: 10,
        porcentajeVictorias: 27,
      },
      {
        equipo: "Inter de Milán",
        pj: 11,
        v: 3,
        e: 3,
        d: 5,
        puntos: 9,
        porcentajeVictorias: 27,
      },
      {
        equipo: "Palermo F.C.",
        pj: 14,
        v: 3,
        e: 2,
        d: 9,
        puntos: 8,
        porcentajeVictorias: 21,
      },
    ],
  },
  {
    nombre: "Jornada 5",
    resultados: [
      {
        equipo: "Sporting Lisboa",
        pj: 18,
        v: 11,
        e: 2,
        d: 5,
        puntos: 24,
        porcentajeVictorias: 61,
      },
      {
        equipo: "Galatasaray SK",
        pj: 16,
        v: 9,
        e: 2,
        d: 5,
        puntos: 20,
        porcentajeVictorias: 56,
      },
      {
        equipo: "Fiorentina",
        pj: 17,
        v: 8,
        e: 3,
        d: 6,
        puntos: 19,
        porcentajeVictorias: 47,
      },
      {
        equipo: "Borussia Dortmund",
        pj: 16,
        v: 6,
        e: 3,
        d: 7,
        puntos: 15,
        porcentajeVictorias: 38,
      },
      {
        equipo: "Inter de Milán",
        pj: 15,
        v: 6,
        e: 2,
        d: 7,
        puntos: 14,
        porcentajeVictorias: 40,
      },
      {
        equipo: "París Saint-Germain",
        pj: 15,
        v: 6,
        e: 1,
        d: 8,
        puntos: 13,
        porcentajeVictorias: 40,
      },
      {
        equipo: "Tottenham Hotspur",
        pj: 14,
        v: 5,
        e: 1,
        d: 8,
        puntos: 11,
        porcentajeVictorias: 36,
      },
      {
        equipo: "Palermo F.C.",
        pj: 14,
        v: 5,
        e: 1,
        d: 8,
        puntos: 11,
        porcentajeVictorias: 36,
      },
      {
        equipo: "Arsenal F.C.",
        pj: 13,
        v: 4,
        e: 3,
        d: 6,
        puntos: 11,
        porcentajeVictorias: 31,
      },
    ],
  },
  {
    nombre: "Jornada 6",
    resultados: [
      {
        equipo: "Palermo F.C.",
        pj: 23,
        v: 12,
        e: 3,
        d: 8,
        puntos: 27,
        porcentajeVictorias: 52,
      },
      {
        equipo: "París Saint-Germain",
        pj: 23,
        v: 12,
        e: 1,
        d: 10,
        puntos: 25,
        porcentajeVictorias: 52,
      },
      {
        equipo: "Tottenham Hotspur",
        pj: 14,
        v: 7,
        e: 2,
        d: 5,
        puntos: 16,
        porcentajeVictorias: 50,
      },
      {
        equipo: "Borussia Dortmund",
        pj: 16,
        v: 5,
        e: 6,
        d: 5,
        puntos: 16,
        porcentajeVictorias: 31,
      },
      {
        equipo: "Sporting Lisboa",
        pj: 15,
        v: 6,
        e: 3,
        d: 6,
        puntos: 15,
        porcentajeVictorias: 40,
      },
      {
        equipo: "Galatasaray SK",
        pj: 13,
        v: 6,
        e: 2,
        d: 5,
        puntos: 14,
        porcentajeVictorias: 46,
      },
      {
        equipo: "Arsenal F.C.",
        pj: 14,
        v: 5,
        e: 3,
        d: 6,
        puntos: 13,
        porcentajeVictorias: 36,
      },
      {
        equipo: "Fiorentina",
        pj: 12,
        v: 3,
        e: 4,
        d: 5,
        puntos: 10,
        porcentajeVictorias: 25,
      },
      {
        equipo: "Inter de Milán",
        pj: 16,
        v: 4,
        e: 2,
        d: 10,
        puntos: 10,
        porcentajeVictorias: 25,
      },
    ],
  },
];

const GOLEADORES_L18: { jugador: string; goles: number }[] = [
  { jugador: "José Hernández", goles: 20 },
  { jugador: "Juanse López", goles: 18 },
  { jugador: "Eduardo Sarmiento (Mou)", goles: 15 },
  { jugador: "Ruber Martínez", goles: 15 },
  { jugador: "Ronald Rojas", goles: 12 },
  { jugador: "Steven Cubides", goles: 12 },
  { jugador: "Hernán Medrano", goles: 11 },
  { jugador: "José Franco", goles: 10 },
  { jugador: "Juan DLC", goles: 10 },
  { jugador: "Santiago Corzo", goles: 10 },
  { jugador: "Eduardo Carrillo (Musiala)", goles: 9 },
  { jugador: "Fabricio Rizo", goles: 8 },
  { jugador: "Jürgen Hassler", goles: 8 },
  { jugador: "Kevin Pineda", goles: 8 },
  { jugador: "Roberto Arrieta (Cante)", goles: 8 },
  { jugador: "Sebastián Castaño", goles: 8 },
  { jugador: "Andrés Farfán", goles: 7 },
  { jugador: "Camilo Laborde", goles: 7 },
  { jugador: "Jeison Santa", goles: 7 },
  { jugador: "Jesús Bullones", goles: 7 },
  { jugador: "Juanda Dybala", goles: 7 },
  { jugador: "Víctor Castilla (Toto)", goles: 7 },
  { jugador: "Yassir Fuentes", goles: 7 },
  { jugador: "Jesús Vergara (Chula)", goles: 6 },
  { jugador: "Keiler Fonseca", goles: 6 },
  { jugador: "Frederick Molina", goles: 5 },
  { jugador: "Héctor Duque", goles: 5 },
  { jugador: "José Mosquera", goles: 5 },
  { jugador: "Luis Serje", goles: 4 },
  { jugador: "Camilo Yepes", goles: 3 },
  { jugador: "Edwin Martínez", goles: 3 },
  { jugador: "Eudes Pavajeau", goles: 3 },
  { jugador: "Jaime Machado", goles: 3 },
  { jugador: "Jereimy Niebles", goles: 3 },
  { jugador: "Juan Sánchez", goles: 3 },
  { jugador: "Kevin Gómez", goles: 3 },
  { jugador: "Luis Suárez", goles: 3 },
  { jugador: "Andrés Valle", goles: 2 },
  { jugador: "Andy Córdoba (Pingui)", goles: 2 },
  { jugador: "Emanuel Navarro (Goat)", goles: 2 },
  { jugador: "Frank Ramírez", goles: 2 },
  { jugador: "Henry Hernández", goles: 2 },
  { jugador: "Jairo Galván", goles: 2 },
  { jugador: "Jesús Pertuz", goles: 2 },
  { jugador: "Jhan C. Martínez", goles: 2 },
  { jugador: "Juanse Pinedo", goles: 2 },
  { jugador: "Orlando Díaz", goles: 2 },
  { jugador: "Óscar Mendoza", goles: 2 },
  { jugador: "Víctor López", goles: 2 },
  { jugador: "Youseth Nacith", goles: 2 },
  { jugador: "Andrés Cuadrado", goles: 1 },
  { jugador: "Cristian (Azul)", goles: 1 },
  { jugador: "Cristian Benjumea", goles: 1 },
  { jugador: "Daniel Cuadros", goles: 1 },
  { jugador: "David Carballo", goles: 1 },
  { jugador: "Elías Lacera", goles: 1 },
  { jugador: "Fernando Gómez", goles: 1 },
  { jugador: "Javier Cajamarca", goles: 1 },
  { jugador: "Jesús Solano", goles: 1 },
  { jugador: "Juan Mora", goles: 1 },
  { jugador: "Julian Charris", goles: 1 },
  { jugador: "Mario Contreras", goles: 1 },
  { jugador: "Narent Rojas", goles: 1 },
  { jugador: "Nico Yamal", goles: 1 },
  { jugador: "Alexander Benítez", goles: 0 },
  { jugador: "Arnold Castillo", goles: 0 },
  { jugador: "Brayan Cadena", goles: 0 },
  { jugador: "Brayan Ospino", goles: 0 },
  { jugador: "Carlos Armenta", goles: 0 },
  { jugador: "Carlos Romero", goles: 0 },
  { jugador: "Carlos Vega", goles: 0 },
  { jugador: "Darío Daza", goles: 0 },
  { jugador: "Emanuel Celedón", goles: 0 },
  { jugador: "Hernán García", goles: 0 },
  { jugador: "Jainer Álvarez", goles: 0 },
  { jugador: "Jefferson Maestre (El Topi)", goles: 0 },
  { jugador: "José Viña", goles: 0 },
  { jugador: "Junior Duran", goles: 0 },
  { jugador: "Keyner Vides", goles: 0 },
  { jugador: "Leonardo Cadena", goles: 0 },
  { jugador: "Luis Fonseca", goles: 0 },
  { jugador: "Pipe Castillejo", goles: 0 },
];

export const LIGA_18 = {
  tablaGeneral: [
    {
      equipo: "Arsenal F.C.",
      pj: 95,
      victorias: 43,
      empates: 22,
      derrotas: 30,
      porcentajeVictorias: 45,
      puntos: 108,
    },
    {
      equipo: "Borussia Dortmund",
      pj: 98,
      victorias: 44,
      empates: 20,
      derrotas: 34,
      porcentajeVictorias: 45,
      puntos: 108,
    },
    {
      equipo: "Sporting Lisboa",
      pj: 92,
      victorias: 40,
      empates: 21,
      derrotas: 31,
      porcentajeVictorias: 43,
      puntos: 101,
    },
    {
      equipo: "Tottenham Hotspur",
      pj: 95,
      victorias: 42,
      empates: 15,
      derrotas: 38,
      porcentajeVictorias: 44,
      puntos: 99,
    },
    {
      equipo: "París Saint-Germain",
      pj: 95,
      victorias: 41,
      empates: 15,
      derrotas: 39,
      porcentajeVictorias: 43,
      puntos: 97,
    },
    {
      equipo: "Galatasaray SK",
      pj: 87,
      victorias: 34,
      empates: 17,
      derrotas: 36,
      porcentajeVictorias: 39,
      puntos: 85,
    },
    {
      equipo: "Fiorentina",
      pj: 81,
      victorias: 30,
      empates: 21,
      derrotas: 30,
      porcentajeVictorias: 37,
      puntos: 81,
    },
    {
      equipo: "Palermo F.C.",
      pj: 96,
      victorias: 34,
      empates: 13,
      derrotas: 49,
      porcentajeVictorias: 35,
      puntos: 81,
    },
    {
      equipo: "Inter de Milán",
      pj: 85,
      victorias: 28,
      empates: 13,
      derrotas: 44,
      porcentajeVictorias: 33,
      puntos: 69,
    },
  ],
  jornadas: J18,
  goleadoresTotales: GOLEADORES_L18,
  goleadorLiga: { jugador: "José Hernández", goles: 20 },
  arqueros: [
    { arquero: "Brayan Ospino", golesRecibidos: 30 },
    { arquero: "Keyner Vides", golesRecibidos: 30 },
    { arquero: "Brayan Cadena", golesRecibidos: 31 },
    { arquero: "Santiago Sánchez", golesRecibidos: 34 },
    { arquero: "Hernán García", golesRecibidos: 36 },
    { arquero: "Fernando Gómez", golesRecibidos: 38 },
    { arquero: "Luiska Fonseca", golesRecibidos: 39 },
    { arquero: "Leonardo Cadena", golesRecibidos: 44 },
    { arquero: "Pipe Castillejo", golesRecibidos: 49 },
  ],
  mejorArquero: { arquero: "Brayan Ospino", golesRecibidos: 30 },
  cuartos: [] as string[],
  semifinales: [] as string[],
  final: "Por definir",
  ganador: "—",
};
