export type Posicion = "arquero" | "defensa" | "mediocampista" | "delantero";

export interface UsuarioLiga {
  name: string;
  username: string;
  avatar?: string | null;
  ligasJugadas: number;
  esFundador?: boolean;
  ligasGanadas: number;
  esAdmin: boolean;
  golesTotales: number;
  posicion: Posicion;
}



export const USUARIOS_LIGA: UsuarioLiga[] = [
  {
    name: "Mariano Amaris",
    username: "sirama",
    avatar: null,
    ligasJugadas: 17,
    esFundador: true,
    ligasGanadas: 4,
    esAdmin: true,
    golesTotales: 59,
    posicion: "mediocampista",
  },
  {
    name: "Juan de la Cruz",
    username: "jdlc",
    avatar: null,
    ligasJugadas: 18,
    esFundador: true,
    ligasGanadas: 2,
    esAdmin: true,
    golesTotales: 161,
    posicion: "delantero",
  },
  {
    name: "Juan Mora",
    username: "jmora",
    avatar: null,
    ligasJugadas: 18,
    esFundador: true,
    ligasGanadas: 3,
    esAdmin: true,
    golesTotales: 19,
    posicion: "defensa",
  },

  {
    name: "Elias Lacera",
    username: "elacera",
    avatar: null,
    ligasJugadas: 18,
    esFundador: true,
    ligasGanadas: 1,
    esAdmin: true,
    golesTotales: 28,
    posicion: "mediocampista",
  },
  {
    name: "Andy Cordoba",
    username: "acordoba",
    avatar: null,
    ligasJugadas: 10,
    esFundador: false,
    ligasGanadas: 3,
    esAdmin: true,
    golesTotales: 64,
    posicion: "mediocampista",
  },
  {
    name: "Jesús Pertuz",
    username: "jpertuz",
    avatar: null,
    ligasJugadas: 8,
    esFundador: false,
    ligasGanadas: 2,
    esAdmin: true,
    golesTotales: 25,
    posicion: "defensa",
  },
  {
    name: "Eudes Pavajeau",
    username: "epavajeau",
    avatar: null,
    ligasJugadas: 17,
    esFundador: false,
    ligasGanadas: 4,
    esAdmin: true,
    golesTotales: 49,
    posicion: "delantero",
  },
  {
    name: "Fabricio Rizo",
    username: "frizo",
    avatar: null,
    ligasJugadas: 16,
    esFundador: true,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 102,
    posicion: "delantero",
  },
  {
    name: "Emanuel Navarro",
    username: "enavarro",
    avatar: null,
    ligasJugadas: 11,
    esFundador: false,
    ligasGanadas: 7,
    esAdmin: false,
    golesTotales: 153,
    posicion: "delantero",
  },
  {
    name: "Lucas Benjumea",
    username: "lbenjumea",
    avatar: null,
    ligasJugadas: 8,
    esFundador: false,
    ligasGanadas: 3,
    esAdmin: false,
    golesTotales: 56,
    posicion: "delantero",
  },
  {
    name: "Henry Hernandez",
    username: "hhernandez",
    avatar: null,
    ligasJugadas: 18,
    esFundador: true,
    ligasGanadas: 2,
    esAdmin: false,
    golesTotales: 68,
    posicion: "defensa",
  },
  {
    name: "Andres Farfán",
    username: "afarfan",
    avatar: null,
    ligasJugadas: 14,
    esFundador: false,
    ligasGanadas: 3,
    esAdmin: false,
    golesTotales: 200,
    posicion: "delantero",
  },
  {
    name: "Jhonnier de la Cruz",
    username: "jhdlc",
    avatar: null,
    ligasJugadas: 15,
    esFundador: false,
    ligasGanadas: 2,
    esAdmin: false,
    golesTotales: 18,
    posicion: "defensa",
  },
  {
    name: "Jose Henao",
    username: "jhenao",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 1,
    esAdmin: false,
    golesTotales: 10,
    posicion: "delantero",
  },
  {
    name: "Jairo Galván",
    username: "jgalvan",
    avatar: null,
    ligasJugadas: 11,
    esFundador: false,
    ligasGanadas: 3,
    esAdmin: false,
    golesTotales: 106,
    posicion: "delantero",
  },
  {
    name: "Cristian Benjumea",
    username: "cbenjumea",
    avatar: null,
    ligasJugadas: 16,
    esFundador: true,
    ligasGanadas: 5,
    esAdmin: false,
    golesTotales: 67,
    posicion: "defensa",
  },
  {
    name: "Frank Ramirez",
    username: "framirez",
    avatar: null,
    ligasJugadas: 10,
    esFundador: false,
    ligasGanadas: 5,
    esAdmin: false,
    golesTotales: 33,
    posicion: "defensa",
  },

  {
    name: "Ronaldo",
    username: "ronaldo",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 1,
    esAdmin: false,
    golesTotales: 7,
    posicion: "delantero",
  },

  {
    name: "Emanuel Celedón",
    username: "eceledon",
    avatar: null,
    ligasJugadas: 18,
    esFundador: true,
    ligasGanadas: 2,
    esAdmin: false,
    golesTotales: 50,
    posicion: "mediocampista",
  },
  {
    name: "Edward Brito (Titi)",
    username: "ebrito",
    avatar: null,
    ligasJugadas: 7,
    esFundador: false,
    ligasGanadas: 1,
    esAdmin: false,
    golesTotales: 18,
    posicion: "mediocampista",
  },
  {
    name: "José Maestre (Monchi)",
    username: "jmaestre",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 1,
    posicion: "mediocampista",
  },
  {
    name: "Daniel Cuadros",
    username: "dcuadros",
    avatar: null,
    ligasJugadas: 12,
    esFundador: false,
    ligasGanadas: 3,
    esAdmin: false,
    golesTotales: 25,
    posicion: "defensa",
  },
  {
    name: "Esteban Galván",
    username: "egalvan",
    avatar: null,
    ligasJugadas: 9,
    esFundador: false,
    ligasGanadas: 2,
    esAdmin: false,
    golesTotales: 49,
    posicion: "defensa",
  },
  {
    name: "Camilo Laborde",
    username: "claborde",
    avatar: null,
    ligasJugadas: 11,
    esFundador: false,
    ligasGanadas: 1,
    esAdmin: false,
    golesTotales: 43,
    posicion: "delantero",
  },
  {
    name: "Sebastian Perez",
    username: "sperez",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 2,
    esAdmin: false,
    golesTotales: 2,
    posicion: "delantero",
  },
  {
    name: "Keni Contreras",
    username: "kcontreras",
    avatar: null,
    ligasJugadas: 9,
    esFundador: false,
    ligasGanadas: 5,
    esAdmin: false,
    golesTotales: 165,
    posicion: "delantero",
  },
  {
    name: "Pier Rizo",
    username: "prizo",
    avatar: null,
    ligasJugadas: 1,
    esFundador: false,
    ligasGanadas: 1,
    esAdmin: false,
    golesTotales: 17,
    posicion: "delantero",
  },
  {
    name: "Jurgen Hassler",
    username: "jhassler",
    avatar: null,
    ligasJugadas: 10,
    esFundador: false,
    ligasGanadas: 2,
    esAdmin: false,
    golesTotales: 206,
    posicion: "delantero",
  },
  {
    name: "Jefferson Almanza",
    username: "jalmanza",
    avatar: null,
    ligasJugadas: 7,
    esFundador: false,
    ligasGanadas: 2,
    esAdmin: false,
    golesTotales: 69,
    posicion: "delantero",
  },
  {
    name: "Frederick Molina",
    username: "fmolina",
    avatar: null,
    ligasJugadas: 12,
    esFundador: false,
    ligasGanadas: 3,
    esAdmin: false,
    golesTotales: 64,
    posicion: "mediocampista",
  },
  {
    name: "Jeison Santa",
    username: "jsanta",
    avatar: null,
    ligasJugadas: 6,
    esFundador: false,
    ligasGanadas: 1,
    esAdmin: false,
    golesTotales: 112,
    posicion: "delantero",
  },
  {
    name: "Victor Lopez",
    username: "vlopez",
    avatar: null,
    ligasJugadas: 4,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 55,
    posicion: "delantero",
  },
  {
    name: "Luis Mariano",
    username: "luisma",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 17,
    posicion: "delantero",
  },
  {
    name: "Nicolas Yamal",
    username: "nyamal",
    avatar: null,
    ligasJugadas: 6,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 46,
    posicion: "delantero",
  },
  {
    name: "Julio David Ochoa",
    username: "jochoa",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 1,
    esAdmin: false,
    golesTotales: 31,
    posicion: "delantero",
  },
  {
    name: "Juan Dybala",
    username: "jdybala",
    avatar: null,
    ligasJugadas: 5,
    esFundador: false,
    ligasGanadas: 1,
    esAdmin: false,
    golesTotales: 63,
    posicion: "delantero",
  },
  {
    name: "Jorge Farfán",
    username: "jfarfan",
    avatar: null,
    ligasJugadas: 1,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 7,
    posicion: "delantero",
  },
  {
    name: "Carlos Armenta",
    username: "carmenta",
    avatar: null,
    ligasJugadas: 6,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 46,
    posicion: "delantero",
  },
  {
    name: "Junior",
    username: "junior",
    avatar: null,
    ligasJugadas: 1,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 3,
    posicion: "mediocampista",
  },
  {
    name: "Omar Peralta",
    username: "operalta",
    avatar: null,
    ligasJugadas: 6,
    esFundador: false,
    ligasGanadas: 1,
    esAdmin: false,
    golesTotales: 22,
    posicion: "delantero",
  },
  {
    name: "José Viña",
    username: "jviña",
    avatar: null,
    ligasJugadas: 7,
    esFundador: false,
    ligasGanadas: 1,
    esAdmin: false,
    golesTotales: 38,
    posicion: "defensa",
  },
  {
    name: "Ronald Rojas",
    username: "rrojas",
    avatar: null,
    ligasJugadas: 7,
    esFundador: false,
    ligasGanadas: 4,
    esAdmin: false,
    golesTotales: 71,
    posicion: "delantero",
  },
  {
    name: "Julian Charris",
    username: "jcharris",
    avatar: null,
    ligasJugadas: 5,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 16,
    posicion: "defensa",
  },
  {
    name: "Cristian Trujillo",
    username: "ctrujillo",
    avatar: null,
    ligasJugadas: 5,
    esFundador: false,
    ligasGanadas: 2,
    esAdmin: false,
    golesTotales: 29,
    posicion: "delantero",
  },
  {
    name: "Yassir Fuentes",
    username: "yfuentes",
    avatar: null,
    ligasJugadas: 7,
    esFundador: false,
    ligasGanadas: 3,
    esAdmin: false,
    golesTotales: 94,
    posicion: "delantero",
  },

  {
    name: "Narent Rojas",
    username: "nrojas",
    avatar: null,
    ligasJugadas: 6,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 27,
    posicion: "defensa",
  },
  {
    name: "Santiago Sanchez",
    username: "ssanchez",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 1,
    esAdmin: false,
    golesTotales: 4,
    posicion: "arquero",
  },
  {
    name: "Brayan ospino",
    username: "bospino",
    avatar: null,
    ligasJugadas: 7,
    esFundador: false,
    ligasGanadas: 1,
    esAdmin: false,
    golesTotales: 1,
    posicion: "arquero",
  },
  {
    name: "Oscar Perez",
    username: "operez",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 1,
    esAdmin: false,
    golesTotales: 2,
    posicion: "delantero",
  },
  {
    name: "Carlos Barraza",
    username: "cbarraza",
    avatar: null,
    ligasJugadas: 1,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 0,
    posicion: "arquero",
  },
  {
    name: "Juan Vargas",
    username: "jvargas",
    avatar: null,
    ligasJugadas: 1,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 0,
    posicion: "defensa",
  },
  {
    name: "Keiler Fonseca",
    username: "kfonseca",
    avatar: null,
    ligasJugadas: 6,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 65,
    posicion: "delantero",
  },
  {
    name: "David Carballo",
    username: "dcarballo",
    avatar: null,
    ligasJugadas: 6,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 3,
    posicion: "delantero",
  },
  {
    name: "Kevin Pineda",
    username: "kpineda",
    avatar: null,
    ligasJugadas: 7,
    esFundador: false,
    ligasGanadas: 2,
    esAdmin: false,
    golesTotales: 60,
    posicion: "delantero",
  },
  {
    name: "Keyner Vides",
    username: "kvides",
    avatar: null,
    ligasJugadas: 3,
    esFundador: false,
    ligasGanadas: 3,
    esAdmin: false,
    golesTotales: 0,
    posicion: "arquero",
  },
  {
    name: "Sergio Barrera",
    username: "sbarrera",
    avatar: null,
    ligasJugadas: 6,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 32,
    posicion: "delantero",
  },
  {
    name: "Esteban Hinojosa",
    username: "ehinojosa",
    avatar: null,
    ligasJugadas: 7,
    esFundador: false,
    ligasGanadas: 1,
    esAdmin: false,
    golesTotales: 17,
    posicion: "defensa",
  },
  {
    name: "Juan Tellez",
    username: "jtellez",
    avatar: null,
    ligasJugadas: 1,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 0,
    posicion: "mediocampista",
  },
  {
    name: "Juan Sebastian Pinedo",
    username: "jpinedo",
    avatar: null,
    ligasJugadas: 5,
    esFundador: false,
    ligasGanadas: 1,
    esAdmin: false,
    golesTotales: 4,
    posicion: "delantero",
  },
  {
    name: "Camilo Torres",
    username: "ctorres",
    avatar: null,
    ligasJugadas: 1,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 10,
    posicion: "delantero",
  },
  {
    name: "Jorge Cotez",
    username: "jcotez",
    avatar: null,
    ligasJugadas: 1,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 0,
    posicion: "arquero",
  },
  {
    name: "Ronald Andrade",
    username: "randrade",
    avatar: null,
    ligasJugadas: 5,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 3,
    posicion: "delantero",
  },
  {
    name: "Mario Orozco",
    username: "morozco",
    avatar: null,
    ligasJugadas: 7,
    esFundador: false,
    ligasGanadas: 1,
    esAdmin: false,
    golesTotales: 40,
    posicion: "delantero",
  },
  {
    name: "Jose Mosquera",
    username: "jmosquera",
    avatar: null,
    ligasJugadas: 7,
    esFundador: false,
    ligasGanadas: 2,
    esAdmin: false,
    golesTotales: 46,
    posicion: "delantero",
  },
  {
    name: "Fernando Gomez",
    username: "fgomez",
    avatar: null,
    ligasJugadas: 10,
    esFundador: false,
    ligasGanadas: 1,
    esAdmin: false,
    golesTotales: 2,
    posicion: "arquero",
  },
  {
    name: "Juan Sebastian Tibaduiza",
    username: "jtibaduiza",
    avatar: null,
    ligasJugadas: 1,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 0,
    posicion: "defensa",
  },
  {
    name: "Carlos Romero",
    username: "cromero",
    avatar: null,
    ligasJugadas: 8,
    esFundador: false,
    ligasGanadas: 1,
    esAdmin: false,
    golesTotales: 45,
    posicion: "defensa",
  },
  {
    name: "Leonardo Cadena",
    username: "lcadena",
    avatar: null,
    ligasJugadas: 5,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 0,
    posicion: "arquero",
  },
  {
    name: "Dairo Martinez",
    username: "dmartinez",
    avatar: null,
    ligasJugadas: 5,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 9,
    posicion: "delantero",
  },
  {
    name: "Andrés Salazar",
    username: "asalazar",
    avatar: null,
    ligasJugadas: 1,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 0,
    posicion: "mediocampista",
  },
  {
    name: "Andres Blanco",
    username: "ablanco",
    avatar: null,
    ligasJugadas: 1,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 0,
    posicion: "mediocampista",
  },
  {
    name: "Santiago Corzo",
    username: "scorzo",
    avatar: null,
    ligasJugadas: 6,
    esFundador: false,
    ligasGanadas: 2,
    esAdmin: false,
    golesTotales: 106,
    posicion: "delantero",
  },
  {
    name: "Bryan Pallares",
    username: "bpallares",
    avatar: null,
    ligasJugadas: 1,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 3,
    posicion: "delantero",
  },
  {
    name: "Carlos Vega",
    username: "cvega",
    avatar: null,
    ligasJugadas: 5,
    esFundador: false,
    ligasGanadas: 1,
    esAdmin: false,
    golesTotales: 2,
    posicion: "delantero",
  },
  {
    name: "Bryan Cadena",
    username: "bcadena",
    avatar: null,
    ligasJugadas: 8,
    esFundador: false,
    ligasGanadas: 4,
    esAdmin: false,
    golesTotales: 0,
    posicion: "arquero",
  },
  {
    name: "Arnold Castillo",
    username: "acastillo",
    avatar: null,
    ligasJugadas: 8,
    esFundador: false,
    ligasGanadas: 1,
    esAdmin: false,
    golesTotales: 54,
    posicion: "delantero",
  },
  {
    name: "Hernán Medrano",
    username: "hmedrano",
    avatar: null,
    ligasJugadas: 10,
    esFundador: false,
    ligasGanadas: 2,
    esAdmin: false,
    golesTotales: 60,
    posicion: "delantero",
  },
  {
    name: "Ian Nedd",
    username: "inedd",
    avatar: null,
    ligasJugadas: 1,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 0,
    posicion: "defensa",
  },
  {
    name: "Nadim Camall",
    username: "ncamall",
    avatar: null,
    ligasJugadas: 5,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 13,
    posicion: "defensa",
  },
  {
    name: "Arnoldo Daza",
    username: "adaza",
    avatar: null,
    ligasJugadas: 1,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 3,
    posicion: "delantero",
  },
  {
    name: "Brayan Salas",
    username: "bsalas",
    avatar: null,
    ligasJugadas: 1,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 4,
    posicion: "delantero",
  },
  {
    name: "Jose Henao 2",
    username: "jhenao2",
    avatar: null,
    ligasJugadas: 1,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 0,
    posicion: "mediocampista",
  },
  {
    name: "Andres Felipe Castillejo",
    username: "acastillejo",
    avatar: null,
    ligasJugadas: 18,
    esFundador: true,
    ligasGanadas: 4,
    esAdmin: false,
    golesTotales: 0,
    posicion: "arquero",
  },
  {
    name: "José Hernández",
    username: "jhernandez",
    avatar: null,
    ligasJugadas: 10,
    esFundador: false,
    ligasGanadas: 2,
    esAdmin: false,
    golesTotales: 240,
    posicion: "delantero",
  },
  {
    name: "Nicolás Baute",
    username: "nbaute",
    avatar: null,
    ligasJugadas: 1,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 0,
    posicion: "arquero",
  },
  {
    name: "José Laborde",
    username: "jlaborde",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 1,
    esAdmin: false,
    golesTotales: 0,
    posicion: "arquero",
  },
  {
    name: "Víctor Castilla (Toto)",
    username: "vcastilla",
    avatar: null,
    ligasJugadas: 6,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 74,
    posicion: "delantero",
  },
  {
    name: "Pipe New",
    username: "pipenew",
    avatar: null,
    ligasJugadas: 5,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 16,
    posicion: "delantero",
  },
  {
    name: "Breiner Corzo (Mene)",
    username: "bcorzomene",
    avatar: null,
    ligasJugadas: 4,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 6,
    posicion: "delantero",
  },
  // Altas desde goleadores históricos (2 ligas + goles oficiales)
  {
    name: "Eduardo Sarmiento (Mou)",
    username: "esarmientomou",
    avatar: null,
    ligasJugadas: 3,
    esFundador: false,
    ligasGanadas: 1,
    esAdmin: false,
    golesTotales: 55,
    posicion: "delantero",
  },
  {
    name: "Jossimar Cujia (Pollo)",
    username: "jcujiapollo",
    avatar: null,
    ligasJugadas: 7,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 45,
    posicion: "delantero",
  },
  {
    name: "José Franco",
    username: "jfranco",
    avatar: null,
    ligasJugadas: 5,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 35,
    posicion: "delantero",
  },
  {
    name: "Steven Cubides",
    username: "scubides",
    avatar: null,
    ligasJugadas: 4,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 31,
    posicion: "mediocampista",
  },
  {
    name: "Edwin Martínez",
    username: "emartinez",
    avatar: null,
    ligasJugadas: 5,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 27,
    posicion: "delantero",
  },
  {
    name: "Ruber Martínez",
    username: "rubermtz",
    avatar: null,
    ligasJugadas: 6,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 21,
    posicion: "delantero",
  },
  {
    name: "Jesús Bullones",
    username: "jbullones",
    avatar: null,
    ligasJugadas: 3,
    esFundador: false,
    ligasGanadas: 1,
    esAdmin: false,
    golesTotales: 20,
    posicion: "delantero",
  },
  {
    name: "Jesús Cartagena",
    username: "jcartagena",
    avatar: null,
    ligasJugadas: 1,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 0,
    posicion: "delantero",
  },
  {
    name: "Roberto Arrieta (Cante)",
    username: "rarrieta",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 20,
    posicion: "delantero",
  },
  {
    name: "Jesús Trespalacios",
    username: "jtrespalacios",
    avatar: null,
    ligasJugadas: 4,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 19,
    posicion: "delantero",
  },
  {
    name: "Juanse López",
    username: "juanselopez",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 18,
    posicion: "delantero",
  },
  {
    name: "Jesús Vergara (Chula)",
    username: "jvergarachula",
    avatar: null,
    ligasJugadas: 5,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 16,
    posicion: "delantero",
  },
  {
    name: "Jaime Machado",
    username: "jmachado",
    avatar: null,
    ligasJugadas: 4,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 15,
    posicion: "mediocampista",
  },
  {
    name: "Kevin Gómez",
    username: "kgomez",
    avatar: null,
    ligasJugadas: 4,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 15,
    posicion: "delantero",
  },
  {
    name: "Sebastian Castaño",
    username: "scastano",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 14,
    posicion: "delantero",
  },
  {
    name: "Óscar Mendoza",
    username: "omendoza",
    avatar: null,
    ligasJugadas: 4,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 13,
    posicion: "mediocampista",
  },
  {
    name: "Anderson Gómez",
    username: "agomez",
    avatar: null,
    ligasJugadas: 4,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 12,
    posicion: "delantero",
  },
  {
    name: "Alexis Marín",
    username: "amarin",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 11,
    posicion: "delantero",
  },
  {
    name: "Héctor Duque",
    username: "hduque",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 2,
    esAdmin: false,
    golesTotales: 10,
    posicion: "mediocampista",
  },
  {
    name: "Hector Vanegas Jr",
    username: "hvanegas",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 0,
    posicion: "mediocampista",
  },
  {
    name: "Jaime Medrano",
    username: "jaimemedrano",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 10,
    posicion: "mediocampista",
  },
  {
    name: "Eduardo Carrillo (Musiala)",
    username: "ecarrillomusiala",
    avatar: null,
    ligasJugadas: 1,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 9,
    posicion: "mediocampista",
  },
  {
    name: "Jesús Solano",
    username: "jsolano",
    avatar: null,
    ligasJugadas: 4,
    esFundador: false,
    ligasGanadas: 2,
    esAdmin: false,
    golesTotales: 8,
    posicion: "delantero",
  },
  {
    name: "Luis Rico",
    username: "lrico",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 7,
    posicion: "delantero",
  },
  {
    name: "Andrés Valle",
    username: "avalle",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 6,
    posicion: "delantero",
  },
  {
    name: "Jefferson Medrano",
    username: "jfmedrano",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 6,
    posicion: "mediocampista",
  },
  {
    name: "Jhan C. Martínez",
    username: "jhanmartinez",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 6,
    posicion: "delantero",
  },
  {
    name: "Luis Serge",
    username: "lserge",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 6,
    posicion: "delantero",
  },
  {
    name: "Miguel Guerra",
    username: "mguerra",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 5,
    posicion: "delantero",
  },
  {
    name: "Juan Sebastian",
    username: "jsebastian",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 4,
    posicion: "delantero",
  },
  {
    name: "Alexander Benitez",
    username: "abenitez",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 3,
    posicion: "defensa",
  },
  {
    name: "Andrés Cuadrado",
    username: "acuadrado",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 3,
    posicion: "mediocampista",
  },
  {
    name: "Camilo Yepes",
    username: "cyepes",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 3,
    posicion: "delantero",
  },
  {
    name: "Carlos López",
    username: "clopez",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 3,
    posicion: "defensa",
  },
  {
    name: "Daniel Trillos",
    username: "dtrillos",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 3,
    posicion: "mediocampista",
  },
  {
    name: "Filgar Morales",
    username: "fmorales",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 3,
    posicion: "delantero",
  },
  {
    name: "Jereimy Niebles",
    username: "jniebles",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 3,
    posicion: "delantero",
  },
  {
    name: "Jeysson Henríquez",
    username: "jhenriquez",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 3,
    posicion: "delantero",
  },
  {
    name: "Juan Sánchez",
    username: "juansanchez",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 3,
    posicion: "delantero",
  },
  {
    name: "Luis Suárez",
    username: "lsuarez",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 3,
    posicion: "delantero",
  },
  {
    name: "Óscar DLC",
    username: "oscardlc",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 3,
    posicion: "mediocampista",
  },
  {
    name: "Alejandro Macherna",
    username: "amacherna",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 2,
    posicion: "mediocampista",
  },
  {
    name: "Antonio Calle",
    username: "acalle",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 2,
    posicion: "mediocampista",
  },
  {
    name: "Jainer Álvarez",
    username: "jalvarez",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 2,
    posicion: "defensa",
  },
  {
    name: "Jorge España",
    username: "jespana",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 2,
    posicion: "mediocampista",
  },
  {
    name: "Orlando Díaz",
    username: "odiaz",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 2,
    posicion: "delantero",
  },
  {
    name: "Youseth Nacith",
    username: "ynacith",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 2,
    posicion: "delantero",
  },
  {
    name: "Andrés Galindo",
    username: "agalindo",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 1,
    posicion: "delantero",
  },
  {
    name: "Daniel Periñan",
    username: "dperinan",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 1,
    posicion: "delantero",
  },
  {
    name: "Daniel Prens",
    username: "dprens",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 1,
    posicion: "delantero",
  },
  {
    name: "Darío Daza",
    username: "ddaza",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 1,
    posicion: "defensa",
  },
  {
    name: "Héctor Díaz",
    username: "hdiaz",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 1,
    posicion: "mediocampista",
  },
  {
    name: "Javier Cajamarca",
    username: "jcajamarca",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 1,
    posicion: "defensa",
  },
  {
    name: "José Carrascal",
    username: "jcarrascal",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 1,
    posicion: "delantero",
  },
  {
    name: "José Celedón",
    username: "jceledon",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 1,
    posicion: "mediocampista",
  },
  {
    name: "Libardo del 5",
    username: "libardo5",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 1,
    posicion: "delantero",
  },
  {
    name: "Lucho Alejandro",
    username: "luchoale",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 1,
    posicion: "mediocampista",
  },
  {
    name: "Meyssal Murillo",
    username: "mmurillo",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 1,
    posicion: "delantero",
  },
  {
    name: "Mario Contreras",
    username: "mcontreras",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 1,
    posicion: "delantero",
  },
  {
    name: "Ronaldo Iglesia",
    username: "riglesia",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 1,
    posicion: "delantero",
  },
  {
    name: "Samuel",
    username: "samuelppt",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 1,
    posicion: "delantero",
  },
];
