export type Posicion = "arquero" | "defensa" | "mediocampista" | "delantero";

export interface UsuarioLiga {
  name: string;
  username: string;
  avatar?: string | null;
  ligasJugadas: number;
  esFundador?: boolean;
  ligasGanadas: number;
  esAdmin: boolean;
  golesTotales: number;
  posicion: Posicion;
}

// Requisitos para ser fundador -> haber jugado todas las ligas

export const USUARIOS_LIGA: UsuarioLiga[] = [
  {
    name: "Mariano Amaris",
    username: "sirama",
    avatar: null,
    ligasJugadas: 13,
    esFundador: true,
    ligasGanadas: 4,
    esAdmin: true,
    golesTotales: 57,
    posicion: "mediocampista",
  },
  {
    name: "Juan de la Cruz",
    username: "jdlc",
    avatar: null,
    ligasJugadas: 13,
    esFundador: true,
    ligasGanadas: 1,
    esAdmin: true,
    golesTotales: 99,
    posicion: "delantero",
  },
  {
    name: "Juan Mora",
    username: "jmora",
    avatar: null,
    ligasJugadas: 13,
    esFundador: true,
    ligasGanadas: 3,
    esAdmin: true,
    golesTotales: 15,
    posicion: "defensa",
  },

  {
    name: "Elias Lacera",
    username: "elacera",
    avatar: null,
    ligasJugadas: 13,
    esFundador: true,
    ligasGanadas: 1,
    esAdmin: true,
    golesTotales: 19,
    posicion: "mediocampista",
  },
  {
    name: "Andy Cordoba",
    username: "acordoba",
    avatar: null,
    ligasJugadas: 7,
    esFundador: false,
    ligasGanadas: 3,
    esAdmin: true,
    golesTotales: 27,
    posicion: "mediocampista",
  },
  {
    name: "Jesús Pertuz",
    username: "jpertuz",
    avatar: null,
    ligasJugadas: 4,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: true,
    golesTotales: 14,
    posicion: "defensa",
  },
  {
    name: "Eudes Pavajeau",
    username: "epavajeau",
    avatar: null,
    ligasJugadas: 12,
    esFundador: false,
    ligasGanadas: 3,
    esAdmin: true,
    golesTotales: 37,
    posicion: "delantero",
  },
  {
    name: "Fabricio Rizo",
    username: "frizo",
    avatar: null,
    ligasJugadas: 13,
    esFundador: true,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 80,
    posicion: "delantero",
  },
  {
    name: "Emanuel Navarro",
    username: "",
    avatar: null,
    ligasJugadas: 11,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 118,
    posicion: "delantero",
  },
  {
    name: "Lucas Benjumea",
    username: "lbenjumea",
    avatar: null,
    ligasJugadas: 6,
    esFundador: false,
    ligasGanadas: 3,
    esAdmin: false,
    golesTotales: 56,
    posicion: "delantero",
  },
  {
    name: "Henry Hernandez",
    username: "hhernandez",
    avatar: null,
    ligasJugadas: 13,
    esFundador: true,
    ligasGanadas: 2,
    esAdmin: false,
    golesTotales: 54,
    posicion: "defensa",
  },
  {
    name: "Andres Felipe Farfán",
    username: "",
    avatar: null,
    ligasJugadas: 11,
    esFundador: false,
    ligasGanadas: 3,
    esAdmin: false,
    golesTotales: 140,
    posicion: "delantero",
  },
  {
    name: "Jhonnier de la Cruz",
    username: "jhdlc",
    avatar: null,
    ligasJugadas: 12,
    esFundador: false,
    ligasGanadas: 2,
    esAdmin: false,
    golesTotales: 13,
    posicion: "defensa",
  },
  {
    name: "Jose Henao",
    username: "jhenao",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 1,
    esAdmin: false,
    golesTotales: 10,
    posicion: "delantero",
  },
  {
    name: "Jairo Galván",
    username: "jgalvan",
    avatar: null,
    ligasJugadas: 8,
    esFundador: false,
    ligasGanadas: 3,
    esAdmin: false,
    golesTotales: 78,
    posicion: "delantero",
  },
  {
    name: "Cristian Benjumea",
    username: "cbenjumea",
    avatar: null,
    ligasJugadas: 13,
    esFundador: true,
    ligasGanadas: 5,
    esAdmin: false,
    golesTotales: 30,
    posicion: "defensa",
  },
  {
    name: "Frank Ramirez",
    username: "",
    avatar: null,
    ligasJugadas: 7,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 19,
    posicion: "defensa",
  },

  {
    name: "Ronaldo",
    username: "",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 7,
    posicion: "delantero",
  },

  {
    name: "Emanuel Celedón",
    username: "",
    avatar: null,
    ligasJugadas: 8,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 27,
    posicion: "mediocampista",
  },
  {
    name: "Edward Brito",
    username: "",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 5,
    posicion: "mediocampista",
  },
  {
    name: "Monchi",
    username: "",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 2,
    posicion: "mediocampista",
  },
  {
    name: "Daniel Cuadros",
    username: "",
    avatar: null,
    ligasJugadas: 5,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 7,
    posicion: "defensa",
  },
  {
    name: "Esteban Galván",
    username: "",
    avatar: null,
    ligasJugadas: 6,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 27,
    posicion: "defensa",
  },
  {
    name: "Camilo Laborde",
    username: "",
    avatar: null,
    ligasJugadas: 6,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 24,
    posicion: "arquero",
  },
  {
    name: "Sebastian Perez",
    username: "",
    avatar: null,
    ligasJugadas: 1,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 2,
    posicion: "delantero",
  },
  {
    name: "Keni Contreras",
    username: "",
    avatar: null,
    ligasJugadas: 7,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 106,
    posicion: "delantero",
  },
  {
    name: "Pier Rizo",
    username: "",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 17,
    posicion: "delantero",
  },
  {
    name: "Jurgen Hassler",
    username: "",
    avatar: null,
    ligasJugadas: 5,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 82,
    posicion: "delantero",
  },
  {
    name: "Jefferson Almanza",
    username: "",
    avatar: null,
    ligasJugadas: 5,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 43,
    posicion: "mediocampista",
  },
  {
    name: "Sergio Blanchar",
    username: "",
    avatar: null,
    ligasJugadas: 4,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 21,
    posicion: "defensa",
  },
  {
    name: "Frederick",
    username: "",
    avatar: null,
    ligasJugadas: 3,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 29,
    posicion: "mediocampista",
  },
  {
    name: "Jeison Santa",
    username: "",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 33,
    posicion: "delantero",
  },
  {
    name: "Victor Lopez",
    username: "",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 31,
    posicion: "delantero",
  },
  {
    name: "Luisma",
    username: "",
    avatar: null,
    ligasJugadas: 1,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 10,
    posicion: "defensa",
  },
  {
    name: "Nicolas Yamal",
    username: "",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 10,
    posicion: "delantero",
  },
  {
    name: "Julio",
    username: "",
    avatar: null,
    ligasJugadas: 1,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 9,
    posicion: "delantero",
  },
  {
    name: "Juanda",
    username: "",
    avatar: null,
    ligasJugadas: 1,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 8,
    posicion: "defensa",
  },
  {
    name: "Jorge Farfán",
    username: "",
    avatar: null,
    ligasJugadas: 1,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 7,
    posicion: "delantero",
  },
  {
    name: "Carlos Armenta",
    username: "",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 15,
    posicion: "defensa",
  },
  {
    name: "Junior",
    username: "",
    avatar: null,
    ligasJugadas: 1,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 3,
    posicion: "defensa",
  },
  {
    name: "Omar Peralta",
    username: "",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 5,
    posicion: "defensa",
  },
  {
    name: "José Viña",
    username: "",
    avatar: null,
    ligasJugadas: 1,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 1,
    posicion: "defensa",
  },
  {
    name: "Ronald Rojas",
    username: "",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 13,
    posicion: "delantero",
  },
  {
    name: "Charris",
    username: "",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 8,
    posicion: "defensa",
  },
  {
    name: "Cristian Trujillo",
    username: "",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 9,
    posicion: "defensa",
  },
  {
    name: "Yassir",
    username: "",
    avatar: null,
    ligasJugadas: 1,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 4,
    posicion: "defensa",
  },

  {
    name: "Narent Rojas",
    username: "",
    avatar: null,
    ligasJugadas: 1,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 2,
    posicion: "defensa",
  },
  {
    name: "Santiago Sanchez",
    username: "",
    avatar: null,
    ligasJugadas: 2,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 4,
    posicion: "arquero",
  },
  {
    name: "Brayan ospino",
    username: "",
    avatar: null,
    ligasJugadas: 1,
    esFundador: false,
    ligasGanadas: 0,
    esAdmin: false,
    golesTotales: 1,
    posicion: "arquero",
  },
];
