# netlify.toml

[[redirects]]
  from = "/wp-admin/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/xmlrpc.php"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/wp-login.php"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/wp-includes/*"
  to = "/404.html"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = "default-src 'self';"
